-- LuaDC version 0.9.19
-- 5/23/2004 7:23:42 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
Ship = 0
SubSystem = 1
build = {

	---Special powers based on energy------------------
    
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ab_inertia", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "isLieutenant",
        DisplayPriority = 100, 
        DisplayedName = "Inertia Drive", 
        Description = "<b>Description:</b> The Progenitor inertia drive system is capable of throwing super heavy capital ships over a remarkably long distance at a velocity only second to the speed of light (despite its questionable destination...)! As a side effect, it will sweep all nearby ships (within 2000m) upon ignition. Only recommended for strategic maneuvers across vast space. \n\n<b>Type:</b> Special Power \n\n<b>Upgraded States:</b> \n<c=0080FF>Advanced</c> - better direction control \n<c=FFF900>Extreme</c> - 200% impulse and recharge rate \n<c=FF0000>Ultimate</c> - instant recharge + reactionless drive without side effects (highly directional travel across 50000m in an instant)! \n\n<b>Prerequisites:</b> \nLieutenant Rank (30 Honor points) \n25 Energy (Stored)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ab_repulsor", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "isCommander",
        DisplayPriority = 110, 
        DisplayedName = "Repulsor", 
        Description = "<b>Description:</b> The aggressive version of the Inertia Drive, outputs all its energy in a single tremendous burst, bouncing if not paralyzing all nearby ships (within 2500m). \n\n<b>Type:</b> Special Power \n\n<b>Upgraded States:</b> \n<c=0080FF>Advanced</c> - 200% recharge rate + 200% EMP effect \n<c=FFF900>Extreme</c> - 5000m bouncing radius \n<c=FF0000>Ultimate</c> - 10000m bouncing radius + 100X bouncing force! \n\n<b>Prerequisites:</b> \nCommander Rank (80 Honor points) \n50 Energy (Stored)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ab_nuke", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "isCaptain", 
        DisplayPriority = 120, 
        DisplayedName = "Gamma Ray Burst", 
        Description = "<b>Description:</b> Projects antimatter to the surroundings to set off annihilation reactions, unleashing a deadly gamma ray burst in the form of pure energy, which causes severe disruption (within 5000m). \n\n<b>Type:</b> Special Power \n\n<b>Upgraded States:</b> \n<c=0080FF>Advanced</c> - 200% burst counts \n<c=FFF900>Extreme</c> - 200% recharge rate + 200% EMP damage \n<c=FF0000>Ultimate</c> - collimated beam can cut anything within 300000m into piecies! \n\n<b>Prerequisites:</b> \nCaptain Rank (150 Honor points) \n75 Energy (Stored)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ab_am", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "isCommodore",
        DisplayPriority = 130, 
        DisplayedName = "Subspace Normalizer", 
        Description = "<b>Description:</b> Deconstruct the fabric of space to create a lower dimension and trap all missiles (within 5000m) inside forever. \n\n<b>Type:</b> Special Power \n\n<b>Upgraded States:</b> \n<c=0080FF>Advanced</c> - a 2-D foil will clear a path by destroying all missiles and mines in the front \n<c=FFF900>Extreme</c> - 200% recharge rate + 200% 2-D foil radius \n<c=FF0000>Ultimate</c> - dimension attack with 200% range + you cannot escape from death! \n\n<b>Prerequisites:</b> \nCommodore Rank (240 Honor points) \n100 Energy (Stored)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ab_blackhole", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "IsAdmiral",
        DisplayPriority = 140, 
        DisplayedName = "Kugelblitz", 
        Description = "<b>Description:</b> Injects an insane amount of energy in the form of light into a singularity to generate a miniature black hole, sucking everything towards it (within 2500m). A miniature black hole can be also used for braking when traveling at high speed. \n\n<b>Type:</b> Special Power \n\n<b>Upgraded States:</b> \n<c=0080FF>Advanced</c> - 200% life span \n<c=FFF900>Extreme</c> - 5000m suction radius \n<c=FF0000>Ultimate</c> - 35000m suction radius + guaranteed spaghettification! \n\n<b>Prerequisites:</b> \nAdmiral Rank (350 Honor points) \n125 Energy (Stored)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ab_particle", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "isFleetAdmiral", 
        DisplayPriority = 150, 
        DisplayedName = "Light Granule", 
        Description = "<b>Description:</b> Extremely deadly and efficient, with a little mass, the Light Granule can destroy almost anything from battleships to even the stars themselves depending on its sheer speed! This weapon is known to be used in galactic warfare and planetary cleansing frequently. \n\n<b>Type:</b> Special Power \n\n<b>Upgraded States:</b> \n<c=0080FF>Advanced</c> - infinite range \n<c=FFF900>Extreme</c> - double strike \n<c=FF0000>Ultimate</c> - travels at lightspeed and cannot be intercepted! \n\n<b>Prerequisites:</b> \nFleet Admiral Rank (480 Honor points) \n150 Energy (Stored)", },

	---Special power icons (for research menu sorting)------------------
		{ 
			  Type = Ship, 			  
			  ThingToBuild = "kpr_specialpower_inertiadrive",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 10,},
		{ 
			  Type = Ship, 			  
			  ThingToBuild = "kpr_specialpower_repulsor",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 20,},
		{ 
			  Type = Ship, 			  
			  ThingToBuild = "kpr_specialpower_gammarayburst",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 30,},
		{ 
			  Type = Ship, 			  
			  ThingToBuild = "kpr_specialpower_dimensionattack",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 40,},
		{ 
			  Type = Ship, 			  
			  ThingToBuild = "kpr_specialpower_blackhole",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 50,},
		{ 
			  Type = Ship, 			  
			  ThingToBuild = "kpr_specialpower_lightgranule",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 60,},

	---Orders------------------
	
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_orders_en100", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "", 
        DisplayPriority = 92, 
        DisplayedName = "100 Energy --> RUs", 
        Description = "<b>Description:</b> Convert 100 Energy into RUs!\n\n<b>Type:</b> Playing God \n\n<b>Prerequisites:</b> \n100 Energy (Stored)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_orders_ru1000", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        RequiredFleetSubSystems = "", 
        DisplayPriority = 95, 
        DisplayedName = "1000 RUs --> Energy", 
        Description = "<b>Description:</b> Convert 1000 RUs into Energy!\n\n<b>Type:</b> Playing God \n\n<b>Prerequisites:</b> \n1000 RUs (Stored)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_clear", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 0, 
        DisplayedName = "Clear Orders", 
        Description = "<b>Description:</b> Clear all permanent orders!\n\n<b>Type:</b> Order", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_parade", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 10, 
        DisplayedName = "Instant Parade", 
        Description = "<b>Description:</b> All units within a limited radius around the ship (7000 m) immediately parade to this ship!\n\n<b>Type:</b> Order", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_guard", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 30, 
        DisplayedName = "Guard", 
        Description = "<b>Description:</b> All units within a limited radius around the ship (7000 m) immediately guard this ship!\n\n<b>Type:</b> Order", },  
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_dock", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 31, 
        DisplayedName = "Auto-Dock", 
        Description = "<b>Description:</b> All fighters and corvettes within a limited radius around the ship (15000 m) immediately dock to this ship if damaged!\n\n<b>Type:</b> Order (permanent)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_deploy", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "heavycruiserPC",
        DisplayPriority = 32, 
        DisplayedName = "Deploy Nuke Cannon", 
        Description = "<b>Description:</b> Deploy the Nuke Cannon! Peacemaker will hold its current position and direction in order to fire long range Nuke Cannon at frontal enemies\n\n<b>Type:</b> Order", },  		
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_unplug", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 33, 
        DisplayedName = "Unplug Generators", 
        Description = "<b>Description:</b> Launch docked Power Generators to disable overcharge links \n\n<b>Type:</b> Order", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_trade", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 19, 
        DisplayedName = "Disable Trading", 
        Description = "<b>Description:</b> Disable Trading on Trade Convoy!\n\n<b>Type:</b> Order (permanent)", },     
    { 
        Type = SubSystem, 
        ThingToBuild = "engine_boost_container", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "", 
        DisplayPriority = 20, 
        DisplayedName = "Engine Boost", 
        Description = "<b>Description:</b> Engine final Boost, improves engine power (+300%), to work properly needs additional energy (-3)\n\n<b>Type:</b> Order", },	 

	---PTV------------------

    { 
        Type = Ship, 
        ThingToBuild = "kpr_meddler", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 3, 
        DisplayedName = "Deadeye", 
        Description = "<b>Description:</b> Automated Sniper, weakly equipped, but has incredible effective range (100000m). \n\n<b>Armament:</b> 1x Random Sniping Weapon \nCost: 1250 RUs \nBuild time: 25 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> 1 crew member", }, 
    { 
        Type = Ship, 
        ThingToBuild = "kpr_meddler1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 3, 
        DisplayedName = "Deadeye", 
        Description = "<b>Description:</b> Automated Sniper, weakly equipped, but has incredible effective range (100000m). \n\n<b>Armament:</b> 1x Random Sniping Weapon \nCost: 1250 RUs \nBuild time: 25 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> 1 crew member", }, 
    { 
        Type = Ship, 
        ThingToBuild = "kpr_marauder", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Angler", 
        Description = "<b>Description:</b> Automated Fishing Boat. \n\n<b>Armament:</b> 1x Quantum Sucker \nCost: 1250 RUs \nBuild time: 25 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> 2 crew members", }, 
    { 
        Type = Ship, 
        ThingToBuild = "kpr_marauder1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Angler", 
        Description = "<b>Description:</b> Automated Fishing Boat. \n\n<b>Armament:</b> 1x Quantum Sucker \nCost: 1250 RUs \nBuild time: 25 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> 2 crew members", }, 
    { 
        Type = Ship, 
        ThingToBuild = "kpr_sentinel", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Acolyte", 
        Description = "<b>Description:</b> Automated Defense Gun. \n\n<b>Armament:</b> 1x Plasma Gattling Gun \nCost: 1250 RUs \nBuild time: 25 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> 4 crew members", }, 
    { 
        Type = Ship, 
        ThingToBuild = "kpr_sentinel1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Acolyte", 
        Description = "<b>Description:</b> Automated Defense Gun. \n\n<b>Armament:</b> 1x Plasma Gattling Gun \nCost: 1250 RUs \nBuild time: 25 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> 4 crew members", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kpr_Mover", 
        RequiredResearch = "MoverTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 53, 
        DisplayedName = "Mover", 
        Description = "<b>Description:</b> Drone designed to disable and tow off enemy ships. \n\n<b>Armament:</b> 1x Energy Cannon, Towing Field (Capture) \nCost: 850 RUs \nBuild time: 15 s \nMaintenance cost: 50 RUs / year \n\n<b>Prerequisites:</b> Awaken Movers \n2 crew members", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kpr_Mover1", 
        RequiredResearch = "MoverTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 53, 
        DisplayedName = "Mover", 
        Description = "<b>Description:</b> Drone designed to disable and tow off enemy ships. \n\n<b>Armament:</b> 1x Energy Cannon, Towing Field (Capture) \nCost: 850 RUs \nBuild time: 15 s \nMaintenance cost: 50 RUs / year \n\n<b>Prerequisites:</b> Awaken Movers \n2 crew members", }, 
   { 
       Type = Ship, 
        ThingToBuild = "kpr_interceptor_combo", 
        RequiredResearch = "AgitatorComboTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 13, 
        DisplayedName = "Agitator Combo", 
        Description = "<b>Description:</b> Dogfight Drone designed to destroy fighters and corvettes. \n\n<b>Combo of:</b> 2x Agitator \n\n<b>Armament:</b> 4x Plasma Repeater \nCost: 1800 RUs \nBuild time: 30 s \nMaintenance cost: 48 RUs / year \n\n<b>Prerequisites:</b> Awaken Agitator Combos \n2 crew members", },
   { 
       Type = Ship, 
        ThingToBuild = "kpr_interceptor_combo1", 
        RequiredResearch = "AgitatorComboTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 13, 
        DisplayedName = "Agitator Combo", 
        Description = "<b>Description:</b> Dogfight Drone designed to destroy fighters and corvettes. \n\n<b>Combo of:</b> 2x Agitator \n\n<b>Armament:</b> 4x Plasma Repeater \nCost: 1800 RUs \nBuild time: 30 s \nMaintenance cost: 48 RUs / year \n\n<b>Prerequisites:</b> Awaken Agitator Combos \n2 crew members", },
   { 
       Type = Ship, 
        ThingToBuild = "kpr_attackdroid_agitator", 
        RequiredResearch = "AgitatorShifterComboTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 14, 
        DisplayedName = "Shifter/Agitator Combo", 
        Description = "<b>Description:</b> Hybrid Drone designed to deal with all kinds of threats. \n\n<b>Combo of:</b> 1x Agitator, 1x Shifter \n\n<b>Armament:</b> 2x Plasma Repeater, 2x Plasma Bomb Launcher \nCost: 1800 RUs \nBuild time: 35 s \nMaintenance cost: 60 RUs / year \n\n<b>Prerequisites:</b> Awaken Agitator/Shifter Combos \n2 crew members", },
   { 
       Type = Ship, 
        ThingToBuild = "kpr_attackdroid_agitator1", 
        RequiredResearch = "AgitatorShifterComboTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 14, 
        DisplayedName = "Shifter/Agitator Combo", 
        Description = "<b>Description:</b> Hybrid Drone designed to deal with all kinds of threats. \n\n<b>Combo of:</b> 1x Agitator, 1x Shifter \n\n<b>Armament:</b> 2x Plasma Repeater, 2x Plasma Bomb Launcher \nCost: 1800 RUs \nBuild time: 35 s \nMaintenance cost: 60 RUs / year \n\n<b>Prerequisites:</b> Awaken Agitator/Shifter Combos \n2 crew members", },
   { 
       Type = Ship, 
        ThingToBuild = "kpr_attackdroid_combo", 
        RequiredResearch = "ShifterComboTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 15, 
        DisplayedName = "Shifter Combo", 
        Description = "<b>Description:</b> Heavy Attack Drone designed to destroy frigates and capital ships. \n\n<b>Combo of:</b> 2x Shifter \n\n<b>Armament:</b> 4x Plasma Bomb Launcher \nCost: 1800 RUs \nBuild time: 40 s \nMaintenance cost: 72 RUs / year \n\n<b>Prerequisites:</b> Awaken Shifter Combos \n2 crew members", },
   { 
       Type = Ship, 
        ThingToBuild = "kpr_attackdroid_combo1", 
        RequiredResearch = "ShifterComboTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 15, 
        DisplayedName = "Shifter Combo", 
        Description = "<b>Description:</b> Heavy Attack Drone designed to destroy frigates and capital ships. \n\n<b>Combo of:</b> 2x Shifter \n\n<b>Armament:</b> 4x Plasma Bomb Launcher \nCost: 1800 RUs \nBuild time: 40 s \nMaintenance cost: 72 RUs / year \n\n<b>Prerequisites:</b> Awaken Shifter Combos \n2 crew members", },
   { 
       Type = Ship, 
        ThingToBuild = "kpr_interceptor_old", 
        RequiredResearch = "AgitatorTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 13, 
        DisplayedName = "Agitator", 
        Description = "<b>Description:</b> Dogfight Droid designed to destroy fighters and corvettes. \n\n<b>Combos:</b> Agitator, Shifter \n\n<b>Armament:</b> 2x Plasma Repeater \nCost: 900 RUs \nBuild time: 15 s \nMaintenance cost: 24 RUs / year \n\n<b>Prerequisites:</b> Awaken Agitators \n1 crew member", },
   { 
       Type = Ship, 
        ThingToBuild = "kpr_interceptor_old1", 
        RequiredResearch = "AgitatorTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 13, 
        DisplayedName = "Agitator", 
        Description = "<b>Description:</b> Dogfight Droid designed to destroy fighters and corvettes. \n\n<b>Combos:</b> Agitator, Shifter \n\n<b>Armament:</b> 2x Plasma Repeater \nCost: 900 RUs \nBuild time: 15 s \nMaintenance cost: 24 RUs / year \n\n<b>Prerequisites:</b> Awaken Agitators \n1 crew member", },
    { 
        Type = Ship, 
        ThingToBuild = "Kpr_AttackDroid", 
        RequiredResearch = "ShifterTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 43, 
        DisplayedName = "Shifter", 
        Description = "<b>Description:</b> Heavy Attack Droid designed to destroy frigates and capital ships. \n\n<b>Combos:</b> Shifter  \n\n<b>Armament:</b> 2x Plasma Bomb Launcher \nCost: 900 RUs \nBuild time: 20 s \nMaintenance cost: 36 RUs / year \n\n<b>Prerequisites:</b> Awaken Shifters \n1 crew member", },
    { 
        Type = Ship, 
        ThingToBuild = "Kpr_AttackDroid1", 
        RequiredResearch = "ShifterTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 43, 
        DisplayedName = "Shifter", 
        Description = "<b>Description:</b> Heavy Attack Droid designed to destroy frigates and capital ships. \n\n<b>Combos:</b> Shifter  \n\n<b>Armament:</b> 2x Plasma Bomb Launcher \nCost: 900 RUs \nBuild time: 20 s \nMaintenance cost: 36 RUs / year \n\n<b>Prerequisites:</b> Awaken Shifters \n1 crew member", },
     { 
         Type = Ship, 
         ThingToBuild = "kpr_hive", 
         RequiredResearch = "HiveTech", 
         RequiredShipSubSystems = "", 
         RequiredFleetSubSystems = "isLieutenant",
         DisplayPriority = 10, 
         DisplayedName = "Hive Carrier", 
         Description = "<b>Description:</b> Support Autonom eqipped with powerful nano-assembly bays and capable of launching attack drones. \n<b>Armament:</b> 1x Hive Spammer \nCost: 6000 RUs \nBuild time: 25 s \nMaintenance cost: 800 RUs / year \n\n<b>Prerequisites:</b> Awaken Hive Carriers \nLieutenant Rank (30 Honor points) \n15 crew members \n1 officer", },
     { 
         Type = Ship, 
         ThingToBuild = "kpr_hive1", 
         RequiredResearch = "HiveTech", 
         RequiredShipSubSystems = "", 
         RequiredFleetSubSystems = "isLieutenant",
         DisplayPriority = 10, 
         DisplayedName = "Hive Carrier", 
         Description = "<b>Description:</b> Support Autonom eqipped with powerful nano-assembly bays and capable of launching attack drones. \n<b>Armament:</b> 1x Hive Spammer \nCost: 6000 RUs \nBuild time: 25 s \nMaintenance cost: 800 RUs / year \n\n<b>Prerequisites:</b> Awaken Hive Carriers \nLieutenant Rank (30 Honor points) \n15 crew members \n1 officer", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_destroyer", 
        RequiredResearch = "KeeperTech", 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isCommander",
        DisplayPriority = 11, 
        DisplayedName = "Keeper", 
        Description = "<b>Description:</b> Automated and highly maneuverable assault Sentient. Carries production and Quantum Inhibitor systems \n\n<b>Armament:</b> 2x Phased Ion Cannons, 8x Nanite Turret\nCost: 6000 RUs \nBuild time: 25 s \nMaintenance cost: 1000 RUs / year \n\n<b>Prerequisites:</b> Awaken Keepers \nCommander Rank (80 Honor points) \n15 crew members \n1 officer", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_destroyer1", 
        RequiredResearch = "KeeperTech", 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isCommander",
        DisplayPriority = 11, 
        DisplayedName = "Keeper", 
        Description = "<b>Description:</b> Automated and highly maneuverable assault Sentient. Carries production and Quantum Inhibitor systems \n\n<b>Armament:</b> 2x Phased Ion Cannons, 8x Nanite Turret\nCost: 6000 RUs \nBuild time: 25 s \nMaintenance cost: 1000 RUs / year \n\n<b>Prerequisites:</b> Awaken Keepers \nCommander Rank (80 Honor points) \n15 crew members \n1 officer", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_carrier", 
        RequiredResearch = "SleeperTech",  -- 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isCaptain", 
        DisplayPriority = 12, 
        DisplayedName = "Sleeper", 
        Description = "<b>Description:</b> Ancient combat/support sentient. \n\n<b>Armament:</b> 4x Phased Ion Cannons, 6x Nannite Turret \nCost: 9000 RUs \nBuild time: 125 s \nMaintenance cost: 1250 RUs / year \n\n<b>Prerequisites:</b> Awaken Sleepers \nCaptain Rank (150 Honor points) \n30 crew members \n2 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_carrier1", 
        RequiredResearch = "SleeperTech",  -- 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isCaptain", 
        DisplayPriority = 12, 
        DisplayedName = "Sleeper", 
        Description = "<b>Description:</b> Ancient combat/support sentient. \n\n<b>Armament:</b> 4x Phased Ion Cannons, 6x Nannite Turret \nCost: 9000 RUs \nBuild time: 125 s \nMaintenance cost: 1250 RUs / year \n\n<b>Prerequisites:</b> Awaken Sleepers \nCaptain Rank (150 Honor points) \n30 crew members \n2 officers", },
     { 
        Type = Ship, 
        ThingToBuild = "kpr_reaver", 
        RequiredResearch = "ReaverTech",  -- 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isCommodore",
        DisplayPriority = 13, 
        DisplayedName = "Reaver", 
        Description = "<b>Description:</b> Sentient warship designed for frontal assaults. \n\n<b>2x Generator Unlocks:</b> Advanced Phased Ion Array  \n\n<b>Armament:</b> 1x Phased Ion Array \nCost: 9000 RUs \nBuild time: 25 s \nMaintenance cost: 3000 RUs / year \n\n<b>Prerequisites:</b> Awaken Reavers \nCommodore Rank (240 Honor points) \n20 crew members \n2 officers", },
     { 
        Type = Ship, 
        ThingToBuild = "kpr_reaver1", 
        RequiredResearch = "ReaverTech",  -- 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isCommodore",
        DisplayPriority = 13, 
        DisplayedName = "Reaver", 
        Description = "<b>Description:</b> Sentient warship designed for frontal assaults. \n\n<b>2x Generator Unlocks:</b> Advanced Phased Ion Array  \n\n<b>Armament:</b> 1x Phased Ion Array \nCost: 9000 RUs \nBuild time: 25 s \nMaintenance cost: 3000 RUs / year \n\n<b>Prerequisites:</b> Awaken Reavers \nCommodore Rank (240 Honor points) \n20 crew members \n2 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_dreadnaught", 
        RequiredResearch = "DreadnaughtTech",  -- 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "IsAdmiral",
        DisplayPriority = 14, 
        DisplayedName = "Harbinger", 
        Description = "<b>Description:</b> Sentient warship designed to destroy large targets. \n\n<b>2x Generator Unlocks:</b> Advanced Phased Ion Array \n\n<b>Armament:</b> 1x Phased Ion Array, 1x Plasma Repeater Turret, 6x Nanite Turret \nCost: 12000 RUs \nBuild time: 25 s \nMaintenance cost: 7500 RUs / year \n\n<b>Prerequisites:</b> Awaken Harbingers \nAdmiral Rank (350 Honor points) \n35 crew members \n3 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_dreadnaught1", 
        RequiredResearch = "DreadnaughtTech",  -- 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "IsAdmiral",
        DisplayPriority = 14, 
        DisplayedName = "Harbinger", 
        Description = "<b>Description:</b> Sentient warship designed to destroy large targets. \n\n<b>2x Generator Unlocks:</b> Advanced Phased Ion Array \n\n<b>Armament:</b> 1x Phased Ion Array, 1x Plasma Repeater Turret, 6x Nanite Turret \nCost: 12000 RUs \nBuild time: 25 s \nMaintenance cost: 7500 RUs / year \n\n<b>Prerequisites:</b> Awaken Harbingers \nAdmiral Rank (350 Honor points) \n35 crew members \n3 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_sajuuk", 
        RequiredResearch = "SajuukTech", --         
		RequiredShipSubSystems = "", -- 
				RequiredFleetSubSystems = "isFleetAdmiral", 
        DisplayPriority = 16, 
        DisplayedName = "Sajuuk", 		--Devourer
        Description = "<b>Description:</b> Sentient Overlord. \n\n<b>Armament:</b> 1x Advanced Phased Ion Array, 10x Nanite Turret \nCost: 95000 RUs \nBuild time: 250 s \nMaintenance cost: 25000 RUs / year \n\n<b>Prerequisites:</b> Awaken Sajuuk \nFleet Admiral Rank (480 Honor points) \n60 crew members \n6 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_sajuuk1", 
        RequiredResearch = "SajuukTech", --         
		RequiredShipSubSystems = "", -- 
				RequiredFleetSubSystems = "isFleetAdmiral", 
        DisplayPriority = 16, 
        DisplayedName = "Sajuuk", 		--Devourer
        Description = "<b>Description:</b> Sentient Overlord. \n\n<b>Armament:</b> 1x Advanced Phased Ion Array, 10x Nanite Turret \nCost: 95000 RUs \nBuild time: 250 s \nMaintenance cost: 25000 RUs / year \n\n<b>Prerequisites:</b> Awaken Sajuuk \nFleet Admiral Rank (480 Honor points) \n60 crew members \n6 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_shipyard_old", 
        RequiredResearch = "QuantumShifting", --         
		RequiredShipSubSystems = "", -- 
				RequiredFleetSubSystems = "isCommander", 
        DisplayPriority = 1, 
        DisplayedName = "Wormhole", 
        Description = "<b>Description:</b> The Quantum Portal made by Progenitor allows its powerful Sentients to be awakened and summoned anytime and anywhere in the universe. \n\n<b>Armament:</b> None \nCost: 4000 RUs \nBuild time: 150 s \nMaintenance cost: 1500 RUs / year \n\n<b>Prerequisites:</b> Ultra Instinct \nCommander Rank (80 Honor points) \n40 crew members \n3 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_shipyard_old1", 
        RequiredResearch = "QuantumShifting", --         
		RequiredShipSubSystems = "", -- 
				RequiredFleetSubSystems = "isCommander", 
        DisplayPriority = 1, 
        DisplayedName = "Wormhole", 
        Description = "<b>Description:</b> The Quantum Portal made by Progenitor allows its powerful Sentients to be awakened and summoned anytime and anywhere in the universe. \n\n<b>Armament:</b> None \nCost: 4000 RUs \nBuild time: 150 s \nMaintenance cost: 1500 RUs / year \n\n<b>Prerequisites:</b> Ultra Instinct \nCommander Rank (80 Honor points) \n40 crew members \n3 officers", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_resourcecontroller", 
        RequiredResearch = "AwakenTheAutonoms", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 35, 
        DisplayedName = "Minion", 
        Description = "<b>Description:</b> Mobile Resource Drop-Off point, can dock 6 Farmers at once, equipped with: \n6 Resource Drop-Off points \n\n<b>Type:</b> Utility \nCost: 2000 RUs \nBuil time: 120 s \nMaintenance cost: 20 RUs / year \nStrong vs: None \n\n<b>Prerequisites:</b> Awaken Autonoms \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_resourcecontroller1", 
        RequiredResearch = "AwakenTheAutonoms", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 35, 
        DisplayedName = "Minion", 
        Description = "<b>Description:</b> Mobile Resource Drop-Off point, can dock 6 Farmers at once, equipped with: \n6 Resource Drop-Off points \n\n<b>Type:</b> Utility \nCost: 2000 RUs \nBuil time: 120 s \nMaintenance cost: 20 RUs / year \nStrong vs: None \n\n<b>Prerequisites:</b> Awaken Autonoms \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_resourcecollector", 
        RequiredResearch = "AwakenTheAutonoms", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 34, 
        DisplayedName = "Farmer", 
        Description = "<b>Description:</b> Fully automatic resourcing bot, unarmed and untired \n\n<b>Functions:</b> Harvesting \n\n<b>Armament:</b> None \nCost: 850 RUs \nBuild time: 15 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> Awaken Autonoms \n2 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_resourcecollector1", 
        RequiredResearch = "AwakenTheAutonoms", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 34, 
        DisplayedName = "Farmer", 
        Description = "<b>Description:</b> Fully automatic resourcing bot, unarmed and untired \n\n<b>Functions:</b> Harvesting \n\n<b>Armament:</b> None \nCost: 850 RUs \nBuild time: 15 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> Awaken Autonoms \n2 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_ressourcecollector_old", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 33, 
        DisplayedName = "Power Generator", 
        Description = "<b>Description:</b> Power Generator is the all-in-one resourcing unit of Progenitor (9 units max) \n\n<b>Functions:</b> \n Generating Energy \n Storing Energy \n Generating RUs when Energy pool is fully charged \n Converting stored RUs into Energy and the other way around \n Overcharging Phase Cannons when docked \n\n<b>Armament:</b> None \nCost: 1000 RUs \nBuild time: 10 s \nMaintenance cost: 12 RUs / year \n\n<b>Prerequisites:</b> None", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_dronestruct", 
        RequiredResearch = "AwakenTheAutonoms", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 34, 
        DisplayedName = "Construct", 
        Description = "<b>Description:</b> Repair & Utility system capable of repairing Drones and Autonoms as well as receiving allied Trade Vessels. \n\n<b>Armament:</b> None \nCost: 3000 RUs \nBuild time: 25 s \nMaintenance cost: 100 RUs / year \n\n<b>Prerequisites:</b> Awaken Autonoms \n10 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_dronestruct1", 
        RequiredResearch = "AwakenTheAutonoms", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 34, 
        DisplayedName = "Construct", 
        Description = "<b>Description:</b> Repair & Utility system capable of repairing Drones and Autonoms as well as receiving allied Trade Vessels. \n\n<b>Armament:</b> None \nCost: 3000 RUs \nBuild time: 25 s \nMaintenance cost: 100 RUs / year \n\n<b>Prerequisites:</b> Awaken Autonoms \n10 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_probe_old", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 25, 
        DisplayedName = "Percipient", 
        Description = "<b>Description:</b> Automated deep space exploration drone, boosts sensors of nearby allied ships and unlocks sensor upgrades. Best used in large numbers. \nCost: 400 RUs \nBuild time: 15 s \nMaintenance cost: 8 RUs / year \n\n<b>Prerequisites:</b> None" },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_guardian", 
        RequiredResearch = "BruteTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 10, 
        DisplayedName = "Revenant", 
        Description = "<b>Description:</b> Ancient Assault Autonom designed to deal with all kinds of threats \n\n<b>Armament:</b> 1x Long-Range Plasma Cannon \nCost: 2150 RUs \nBuild time: 40 s \nMaintenance cost: 270 RUs / year \n\n<b>Prerequisites:</b> Awaken Revenants \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_guardian1", 
        RequiredResearch = "BruteTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 10, 
        DisplayedName = "Revenant", 
        Description = "<b>Description:</b> Ancient Assault Autonom designed to deal with all kinds of threats \n\n<b>Armament:</b> 1x Long-Range Plasma Cannon \nCost: 2150 RUs \nBuild time: 40 s \nMaintenance cost: 270 RUs / year \n\n<b>Prerequisites:</b> Awaken Revenants \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_deciever", 
        RequiredResearch = "DeceiverTech",  -- 
        RequiredShipSubSystems = "",  -- 
        DisplayPriority = 9, 
        DisplayedName = "Deceiver", 
        Description = "<b>Description:</b> Boarding Autonom equipped with advanced Phased Energy Generators. \n\n<b>Armament:</b> 1x Phased Disassembler, 2x Nano-Swarm Emitter \nCost: 2100 RUs \nBuild time: 25 s \nMaintenance cost: 150 RUs / year \n\n<b>Prerequisites:</b>  Awaken Deceivers \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_deciever1", 
        RequiredResearch = "DeceiverTech",  -- 
        RequiredShipSubSystems = "",  -- 
        DisplayPriority = 9, 
        DisplayedName = "Deceiver", 
        Description = "<b>Description:</b> Boarding Autonom equipped with advanced Phased Energy Generators. \n\n<b>Armament:</b> 1x Phased Disassembler, 2x Nano-Swarm Emitter \nCost: 2100 RUs \nBuild time: 25 s \nMaintenance cost: 150 RUs / year \n\n<b>Prerequisites:</b>  Awaken Deceivers \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_hunter", 
        RequiredResearch = "HunterTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 8, 
        DisplayedName = "Hunter", 
        Description = "<b>Description:</b> Ancient Assault Autonom designed to kill Frigates and Capital Ships \n\n<b>Armament:</b> 1x Phased Ion Cannon Array \nCost: 2050 RUs \nBuild time: 25 s \nMaintenance cost: 200 RUs / year \n\n<b>Prerequisites:</b> Awaken Hunters \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_hunter1", 
        RequiredResearch = "HunterTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 8, 
        DisplayedName = "Hunter", 
        Description = "<b>Description:</b> Ancient Assault Autonom designed to kill Frigates and Capital Ships \n\n<b>Armament:</b> 1x Phased Ion Cannon Array \nCost: 2050 RUs \nBuild time: 25 s \nMaintenance cost: 200 RUs / year \n\n<b>Prerequisites:</b> Awaken Hunters \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_seeker", 
        RequiredResearch = "SeekerTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 7, 
        DisplayedName = "Seeker", 
        Description = "<b>Description:</b> Ancient Assault Autonom capable of manufacturing suicidal Seeker Drones. \n\n<b>Armament:</b> 1x Nannite Cannon, 1x Drone Assembly Bay\nCost: 2050 RUs \nBuild time: 25 s \nMaintenance cost: 70 RUs / year \n\n<b>Prerequisites:</b> Awaken Seekers \n8 crew members", },
    { 
        Type = Ship, 
        ThingToBuild = "kpr_seeker1", 
        RequiredResearch = "SeekerTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 7, 
        DisplayedName = "Seeker", 
        Description = "<b>Description:</b> Ancient Assault Autonom capable of manufacturing suicidal Seeker Drones. \n\n<b>Armament:</b> 1x Nannite Cannon, 1x Drone Assembly Bay\nCost: 2050 RUs \nBuild time: 25 s \nMaintenance cost: 70 RUs / year \n\n<b>Prerequisites:</b> Awaken Seekers \n8 crew members", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ms_fighter", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Drone Uplink", 
        Description = "<B>Description:</B>  Allows Progenitor production ships to research Drone technologies. Enables Corvette Research.  \n\n<b>Type:</b> Corvette Assembly Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None.", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_sensor", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 3, 
        DisplayedName = "AI Uplink Module", 
        Description = "<B>Description:</B>  Links the Sleeper to nearby AI systems, boosting the accuracy and sensors range of nearby ships. \n\n<b>Type:</b> Hyperspace Booster (Takes 1 Module Slot). \n\n<b>Prerequisites:</b> None.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_capital", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Quantum Ring", 
        Description = "<B>Description:</B>  Installs a Hyperspace Uplink, allowing large capital ships to be hyperspaced in from remote production foundries. Enables Capital Ship Research & Production.  \n\n<b>Type:</b> Capital Ship Research & Production Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_corvette", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Drone Uplink", 
        Description = "<B>Description:</B>  Allows Progenitor production ships to research Drone technologies. Enables Corvette Research.  \n\n<b>Type:</b> Corvette Assembly Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None." }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_powercap", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Capacitor Module", 
        Description = "<B>Description:</B>  Installs an Capacitor Module on the Harbinger, boosting the ship's weapon damage considerably.  \n\n<b>Type:</b> Reactor Addon (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None." }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_fighter", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Drone Uplink", 
        Description = "<B>Description:</B>  Allows Keeper production ships to research Drone technologies. Enables Corvette Research.  \n\n<b>Type:</b> Corvette Assembly Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None.", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_frigate", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Autonom Uplink", 
        Description = "<B>Description:</B>  Allows Keeper production ships to research Atonom technologies. Enables Frigate Research.  \n\n<b>Type:</b> Frigate Assembly Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None." }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_autonom", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Autonom Uplink", 
        Description = "<B>Description:</B>  Allows Keeper production ships to research Atonom technologies. Enables Frigate Research.  \n\n<b>Type:</b> Frigate Assembly Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_c_hyperspace", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Quantum Bypass Module", 
        Description = "<B>Description:</B>  Installs a Quantum Bypass Module on this ship, allowing it and nearby ships to hyperpsace faster and at a smaller cost. \n\n<b>Type:</b> Hyperspace Booster (Takes 1 Module Slot). \n\n<b>Prerequisites:</b> None.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ms_frigate", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Autonom Uplink", 
        Description = "<B>Description:</B>  Allows Keeper production ships to research Atonom technologies. Enables Frigate Research.  \n\n<b>Type:</b> Frigate Assembly Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kpr_ms_capital", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Quantum Ring", 
        Description = "<B>Description:</B>  Installs a Hyperspace Uplink, allowing large capital ships to be hyperspaced in from remote production foundries. Enables Capital Ship Research & Production.  \n\n<b>Type:</b> Capital Ship Research & Production Module (Takes 1 Production Slot). \n\n<b>Prerequisites:</b> None.", },



	-- ***************************************************
	-- Complex Simple
	-- ***************************************************
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "revealer1",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "revealer2",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "revealer3",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "isLieutenant",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "isCommander",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
  { 
			  Type = SubSystem, 			  
			  ThingToBuild = "isCaptain",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  			  		        
  { 
			  Type = SubSystem, 			  
			  ThingToBuild = "isCommodore",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "isAdmiral",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
  { 
			  Type = SubSystem, 			  
			  ThingToBuild = "isFleetAdmiral",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_hgn",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_vgr",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_kad",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_rad",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_kpr",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_firepower",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_accuracy",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_health",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_repair",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_sensor",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_radiation",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_speed",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military0",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,}, 
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},   	  
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military1",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},   	  
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military2",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},   
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank1",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,}, 
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank2",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank3",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank4",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "unitbehavior",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "unitbehavior_downgrade",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "hyperspace",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "resource",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "buildspeed",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "resistence",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "ai_antirape",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "ai_unitcap",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "sp_invincible",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},

---crate ships (need to be in the build list or they won't have AI)-------------------------------------
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_UNH_CAStandard",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_VAY_CABattle",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_CAHeavy",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFAssault",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFCloak",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFIon",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFMine",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFSupport",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_UNH_FFAssault",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_UNH_FFIon",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_VAY_FFAssault",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_VAY_FFIonArray",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_C_Bomber",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_C_Gunship",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_C_Interceptor",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_G_Bomber",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_G_Interceptor",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},





}
