subs_templar1 = {"kad_destroyer_sensorpod", "kad_destroyer_inquisitionpod", "kad_destroyer_largepod", "kad_destroyer_multipod", "kad_destroyer_demopod", "kad_destroyer_nebulapod", "kad_destroyer_ionpod", "kad_destroyer_gunpod", "kad_destroyer_superpod"}
Survivor = {}
Survivor[1] = { 
            type = "kad_advancedswarmer", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[2] = { 
            type = "kad_advancedswarmer_old", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[3] = { 
            type = "kad_heavyswarmer_new", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[4] = { 
            type = "kad_pulsarswarmer", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[5] = { 
            type = "kad_swarmer_blood", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[6] = { 
            type = "kad_swarmer_crusader", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[7] = { 
            type = "kad_swarmer_ghost", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[8] = { 
            type = "kad_swarmer_hybrid", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[9] = { 
            type = "kad_swarmer_new", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[10] = { 
            type = "kad_swarmer_zealot", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[11] = { 
            type = "kad_gunpod", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[12] = { 
            type = "kad_ionpod", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[13] = { 
            type = "kad_missilepod", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[14] = { 
            type = "kad_pod_ghost", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[15] = { 
            type = "kad_frig_ghost", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[16] = { 
            type = "kad_multibeam", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[17] = { 
            type = "kad_multibeam_new", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[18] = { 
            type = "kad_multigun", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[19] = { 
            type = "kad_podship", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[20] = { 
            type = "kad_destroyer_real", 
            subsystems = {
	        	{
	       		   index = 0,
	       		   name = subs_templar1[random(9)],
	     		   },
}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[21] = { 
            type = "kad_custodian", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[22] = { 
            type = "kad_destroyer", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[23] = { 
            type = "kad_snail", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
SurvivorNum = 23
PersistantData = 
{ 
    StrikeGroups = {}, 
    Squadrons = 
        { 
        Survivor[random(SurvivorNum)],
        }, 
        
    Research = {}, }