subs_randomturret1 = {"rad_rd1_1", "rad_rd2_1", "rad_rd3_1", "rad_rd4_1"}
subs_randomturret2 = {"rad_rd1_2", "rad_rd2_2", "rad_rd3_2", "rad_rd4_2"}
subs_randomturret3 = {"rad_rd1_3", "rad_rd2_3", "rad_rd3_3", "rad_rd4_3"}
subs_randomturret4 = {"rad_rd1_4", "rad_rd2_4", "rad_rd3_4", "rad_rd4_4"}
subs_randomturret5 = {"rad_rd1_5", "rad_rd2_5", "rad_rd3_5", "rad_rd4_5"}
subs_randomturret6 = {"rad_rd1_6", "rad_rd2_6", "rad_rd3_6", "rad_rd4_6"}
subs_d1 = {"rad_destroyer_ion", "rad_destroyer_laser", "rad_destroyer_plasma", "rad_destroyer_missile", "rad_destroyer_cloak"}
Survivor = {}
Survivor[1] = { 
            type = "rad_merc_scout", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[2] = { 
            type = "rad_merc_fighter", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[3] = { 
            type = "rad_merc_interceptor", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[4] = { 
            type = "rad_merc_bomber", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[5] = { 
            type = "rad_bomber", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[6] = { 
            type = "rad_elitefighter", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[7] = { 
            type = "rad_fencer", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[8] = { 
            type = "rad_interceptor", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[9] = { 
            type = "rad_interceptor_black", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[10] = { 
            type = "rad_merc_corvette", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[11] = { 
            type = "rad_scoutcorvette", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[12] = { 
            type = "rad_guncorvette", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[13] = { 
            type = "rad_empcorvette", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[14] = { 
            type = "rad_jackal", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[15] = { 
            type = "rad_missilecorvette", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[16] = { 
            type = "rad_beamfrigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[17] = { 
            type = "rad_gattlingfrigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[18] = { 
            type = "rad_gunfrigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[19] = { 
            type = "rad_gunfrigate_morgan", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[20] = { 
            type = "rad_merc_frigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[21] = { 
            type = "rad_merc_frigateadv", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[22] = { 
            type = "rad_merc_ioncannonfrigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[23] = { 
            type = "rad_missilefrigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[24] = { 
            type = "rad_merc_cruiser", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[25] = { 
            type = "rad_refurbisheddestroyer", 
            subsystems = {
	        	{
	       		   index = 0,
	       		   name = subs_randomturret1[random(4)],
	     		   },
	        	{
	       		   index = 0,
	       		   name = subs_randomturret2[random(4)],
	     		   },
	     		   {
	       		   index = 0,
	       		   name = subs_randomturret3[random(4)],
	     		   },
	        	{
	       		   index = 0,
	       		   name = subs_randomturret4[random(4)],
	     		   },
	     		   {
	       		   index = 0,
	       		   name = subs_randomturret5[random(4)],
	     		   },
	        	{
	       		   index = 0,
	       		   name = subs_randomturret6[random(4)],
	     		   },
}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[26] = { 
            type = "rad_destroyer", 
            subsystems = {
	        	{
	       		   index = 0,
	       		   name = subs_d1[random(4)],
	     		   },
}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[27] = { 
            type = "rad_helios", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[28] = { 
            type = "rad_merc_battlecruiser", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[29] = { 
            type = "rad_cruiser", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[30] = { 
            type = "rad_cruiser_queen", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[31] = { 
            type = "rad_vanaarjet", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[32] = { 
            type = "rad_qwaarjetii", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[33] = { 
            type = "rad_armsdealer", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[34] = { 
            type = "rad_scud", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[35] = { 
            type = "rad_guntrap", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
Survivor[36] = { 
            type = "rad_powerstation", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, }
SurvivorNum = 36
PersistantData = 
{ 
    StrikeGroups = {}, 
    Squadrons = 
        { 
        Survivor[random(SurvivorNum)],
        }, 
        
    Research = {}, }