-- =============================================================================
-- Homeworld 2 Clean Data Resource Project
-- By S110
-- Version 1.0
-- 02/06/2010
-- Tools used: EditPad Lite, LuaDC version 0.9.19, and Cold Fusion LUA Decompiler v1.0.0
-- =============================================================================

Ship = 0
SubSystem = 1
build = {
	---Primary Perks------------------

    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_clear", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "kad_perks_survivalist | kad_perks_rage | kad_perks_stealth | kad_perks_safefall | kad_perks_training | kad_perks_hitandrun | kad_perks_bounty",
        DisplayPriority = 0, 
        DisplayedName = "Clear Primary Perk", 
        Description = "<b>Description:</b> Clear primary perk on this ship!\n\n<b>Type:</b> Primary Perk", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_survivalist", 
        RequiredResearch = "kad_perks_survivalist", 
        RequiredShipSubSystems = "!(kad_perks_rage | kad_perks_stealth | kad_perks_safefall | kad_perks_training | kad_perks_hitandrun | kad_perks_bounty)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 20, 
        DisplayedName = "Survivalist", 
        Description = "<b>Description:</b> Protects the ship from nebula damage. The more damage the carrier ship takes, the more resistant to nebula damage it becomes. \n\n<b>Type:</b> Primary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nVoidborne", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_rage", 
        RequiredResearch = "kad_perks_rage", 
        RequiredShipSubSystems = "!(kad_perks_survivalist | kad_perks_stealth | kad_perks_safefall | kad_perks_training | kad_perks_hitandrun | kad_perks_bounty)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 25, 
        DisplayedName = "Rage of Kadesh", 
        Description = "<b>Description:</b> Allows the ship to deal more damage driven by rage. The more damage the carrier ship takes, the more firepower it gains. \n\n<b>Type:</b> Primary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nOne Vision", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_stealth", 
        RequiredResearch = "kad_perks_stealth", 
        RequiredShipSubSystems = "!(kad_perks_survivalist | kad_perks_rage | kad_perks_safefall | kad_perks_training | kad_perks_hitandrun | kad_perks_bounty)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 30, 
        DisplayedName = "Stealth", 
        Description = "<b>Description:</b> Allows the ship to gain stealth by disturbing the sensor system of nearby enemy ships. The more damage the carrier ship takes, the more likely it could be detected. \n\n<b>Type:</b> Primary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nDark Forest", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_safefall", 
        RequiredResearch = "kad_perks_safefall", 
        RequiredShipSubSystems = "!(kad_perks_survivalist | kad_perks_rage | kad_perks_stealth | kad_perks_training | kad_perks_hitandrun | kad_perks_bounty)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 35, 
        DisplayedName = "Safe Fall", 
        Description = "<b>Description:</b> Reduces hyperspace damage in case of falling into enemy gravity well. The more damage the carrier ship takes, the more resistant to hyperspace damage it becomes. \n\n<b>Type:</b> Primary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nMaster Navigator", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_training", 
        RequiredResearch = "kad_perks_training", 
        RequiredShipSubSystems = "!(kad_perks_survivalist | kad_perks_rage | kad_perks_stealth | kad_perks_safefall | kad_perks_hitandrun | kad_perks_bounty)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 40, 
        DisplayedName = "Advanced Training", 
        Description = "<b>Description:</b> Multiplies the speed at which the carrier ship gains experience by the means of advanced training. \n\n<b>Type:</b> Primary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nTranscendent Learning", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_hitandrun", 
        RequiredResearch = "kad_perks_hitandrun", 
        RequiredShipSubSystems = "!(kad_perks_survivalist | kad_perks_rage | kad_perks_stealth | kad_perks_safefall | kad_perks_training | kad_perks_bounty)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 45, 
        DisplayedName = "Hit and Run", 
        Description = "<b>Description:</b> Multiplies the firepower when the ship is running at its max speed. The faster the carrier ship travels, the more damage it can deal to enemies.  \n\n<b>Type:</b> Primary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nGalactic Contenter", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_bounty", 
        RequiredResearch = "kad_perks_bounty", 
        RequiredShipSubSystems = "!(kad_perks_survivalist | kad_perks_rage | kad_perks_stealth | kad_perks_safefall | kad_perks_training | kad_perks_hitandrun)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 50, 
        DisplayedName = "Bounty Hunter", 
        Description = "<b>Description:</b> Earns bonus RUs depending on ship's behaviour in battle. The harder the carrier ship fights against its enemies, the more RUs it earns.  \n\n<b>Type:</b> Primary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nHunter-Gatherers", },

	---Secondary Perks------------------

    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_clear1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "kad_perks_damagecontrol | kad_perks_curse | kad_perks_revealer | kad_perks_superheavy | kad_perks_potential | kad_perks_retreat | kad_perks_miracle",
        DisplayPriority = 0, 
        DisplayedName = "Clear Secondary Perk", 
        Description = "<b>Description:</b> Clear secondary perk on this ship!\n\n<b>Type:</b> Secondary Perk", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_damagecontrol", 
        RequiredResearch = "kad_perks_damagecontrol", 
        RequiredShipSubSystems = "!(kad_perks_curse | kad_perks_revealer | kad_perks_superheavy | kad_perks_potential | kad_perks_retreat | kad_perks_miracle)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 40, 
        DisplayedName = "Damage Control", 
        Description = "<b>Description:</b> Damage control allows the ship to last longer in desperate conditions. The more damage the carrier ship takes, the faster it regains its health. \n\n<b>Type:</b> Secondary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nMind over Matter", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_curse", 
        RequiredResearch = "kad_perks_curse", 
        RequiredShipSubSystems = "!(kad_perks_damagecontrol | kad_perks_revealer | kad_perks_superheavy | kad_perks_potential | kad_perks_retreat | kad_perks_miracle)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 25, 
        DisplayedName = "Curse of the Garden", 
        Description = "<b>Description:</b> Cursed by the Garden, the ship becomes hard to be captured. The more damage the carrier ship takes, the easilier it could be captured. \n\n<b>Type:</b> Secondary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nConsecrated Worlds", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_revealer", 
        RequiredResearch = "kad_perks_revealer", 
        RequiredShipSubSystems = "!(kad_perks_damagecontrol | kad_perks_curse | kad_perks_superheavy | kad_perks_potential | kad_perks_retreat | kad_perks_miracle)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 30, 
        DisplayedName = "Revealer", 
        Description = "<b>Description:</b> Reveals cloaked enemy ships and enhance own sensors. The more damage the carrier ship takes, the harder it detects enemy ships. \n\n<b>Type:</b> Secondary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nEternal Vigilance", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_superheavy", 
        RequiredResearch = "kad_perks_superheavy", 
        RequiredShipSubSystems = "!(kad_perks_damagecontrol | kad_perks_curse | kad_perks_revealer | kad_perks_potential | kad_perks_retreat | kad_perks_miracle)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 45, 
        DisplayedName = "Super Heavy", 
        Description = "<b>Description:</b> Increase max health by 50%, giving the carrier ship more advantage when colliding with enemy units. \n\n<b>Type:</b> Secondary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nInterstellar Dominion", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_potential", 
        RequiredResearch = "kad_perks_potential", 
        RequiredShipSubSystems = "!(kad_perks_damagecontrol | kad_perks_curse | kad_perks_revealer | kad_perks_superheavy | kad_perks_retreat | kad_perks_miracle)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 50, 
        DisplayedName = "Potential Energy", 
        Description = "<b>Description:</b> Converts damage into energy. The more damage the carrier ship takes, the more energy it generates. \n\n<b>Type:</b> Secondary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nPerpetual Motion", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_retreat", 
        RequiredResearch = "kad_perks_retreat", 
        RequiredShipSubSystems = "!(kad_perks_damagecontrol | kad_perks_curse | kad_perks_revealer | kad_perks_superheavy | kad_perks_potential | kad_perks_miracle)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 35, 
        DisplayedName = "Retreat", 
        Description = "<b>Description:</b> Dramatically increases self repair rate and docked ships repair rate when the ship is running at high speed. The faster the carrier ship travels, the higher repair rate it gains. \n\n<b>Type:</b> Secondary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nLive Long and Prosper", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_perks_miracle", 
        RequiredResearch = "kad_perks_miracle", 
        RequiredShipSubSystems = "!(kad_perks_damagecontrol | kad_perks_curse | kad_perks_revealer | kad_perks_superheavy | kad_perks_potential | kad_perks_retreat)",
        RequiredFleetSubSystems = "2000ru", 
        DisplayPriority = 20, 
        DisplayedName = "Miracle", 
        Description = "<b>Description:</b> In miracle we thrust! Miracle will happen when the carrier ship is fighting to death. \n\n<b>Type:</b> Secondary Perk \n\n<b>Prerequisites:</b> \n2000 RUs (Stored) \nEndtime Prerogative", },


	---Orders------------------

    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_needle", 
        RequiredResearch = "", 
     		RequiredFleetSubSystems = "isFleetAdmiral & !kad_needle_boost", 
        DisplayPriority = 100, 
        DisplayedName = "Reincarnation", 
        Description = "<b>Description:</b> Sacrifice the life of this ship in order to resurrect the Needleship in the form of reincarnation! \n<b><c=ff0000>THIS SHIP WILL BE DESTROYED!</c></b>\n\n<b>Type:</b> Order \n\n<b>Prerequisites:</b> \nFleet Admiral Rank \nno Needleship left", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_clear", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 0, 
        DisplayedName = "Clear Orders", 
        Description = "<b>Description:</b> Clear all permanent orders!\n\n<b>Type:</b> Order", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_parade", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 10, 
        DisplayedName = "Instant Parade", 
        Description = "<b>Description:</b> All units within a limited radius around the ship (7000 m) immediately parade to this ship!\n\n<b>Type:</b> Order", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_guard", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 30, 
        DisplayedName = "Guard", 
        Description = "<b>Description:</b> All units within a limited radius around the ship (7000 m) immediately guard this ship!\n\n<b>Type:</b> Order", },  
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_dock", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 31, 
        DisplayedName = "Auto-Dock", 
        Description = "<b>Description:</b> All fighters and corvettes within a limited radius around the ship (15000 m) immediately dock to this ship if damaged!\n\n<b>Type:</b> Order (permanent)", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_deploy", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "heavycruiserPC",
        DisplayPriority = 32, 
        DisplayedName = "Deploy Nuke Cannon", 
        Description = "<b>Description:</b> Deploy the Nuke Cannon! Peacemaker will hold its current position and direction in order to fire long range Nuke Cannon at frontal enemies\n\n<b>Type:</b> Order", },  		
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_mechanic", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 33, 
        DisplayedName = "Mechanic Support", 
        Description = "<b>Description:</b> Automatically repair idle ships by docking them to the carrier ship within a limited radius (10000 m) if their health is less than 75% \n\n<b>Type:</b> Order", },
    { 
        Type = SubSystem, 
        ThingToBuild = "hgn_orders_trade", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",
        DisplayPriority = 19, 
        DisplayedName = "Disable Trading", 
        Description = "<b>Description:</b> Disable Trading on Trade Convoy!\n\n<b>Type:</b> Order (permanent)", },     
    { 
        Type = SubSystem, 
        ThingToBuild = "engine_boost_container", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "", 
        DisplayPriority = 20, 
        DisplayedName = "Engine Boost", 
        Description = "<b>Description:</b> Engine final Boost, improves engine power (+300%), to work properly needs additional energy (-3)\n\n<b>Type:</b> Order", },	 


    { 
        Type = SubSystem, 
        ThingToBuild = "kad_d_module_1gresearch", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Theological Seminary", 
        Description = "<b>Description:</b> Unlocks the first level of Beliefs to guide Kadeshi to their divinity, also adds 15% health to the carrier ship \n\n<b>Type:</b> Special (takes 1 special slot) \nCost: 4000 RUs \nBuild time: 100 s \n\n<b>Prerequisites:</b> \nNone", },	
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_d_module_hyperspace", 
        RequiredResearch = "HyperspaceTech", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Hyperspace Amplifier", 
        Description = "<b>Description:</b> Allows nearby ships to access hyperspace \n\n<b>Type:</b> Special (takes 1 special slot) \nCost: 3000 RUs \nBuild time: 60 s \n\n<b>Prerequisites:</b> \nQuantum Scriptures", },	
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_d_module_hyperspaceinhibitor", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 3, 
        DisplayedName = "Gravity Well Generator", 
        Description = "<b>Description:</b> Hyperspace inhibitor, prevents enemy ships from entering or exiting hyperspace within a limited radius around the carrier ship \n\n<b>Type:</b> Special (takes 1 special slot) \nCost: 2000 RUs \nBuild time: 50 s \n\n<b>Prerequisites:</b> \nNone", },	
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_d_module_cloakgenerator", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 4, 
        DisplayedName = "Telepathic Complex", 
        Description = "<b>Description:</b> Enhance sensor sensitivity in various aspects, also unlocks Remote Monitor upgrades \n\n<b>Type:</b> Special (takes 1 special slot) \nCost: 1000 RUs \nBuild time: 30 s \n\n<b>Prerequisites:</b> \nNone", },	
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_needle_frig", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isCommander",
        DisplayPriority = 1, 
        DisplayedName = "Cathedral", 
        Description = "<b>Description:</b> Frigate/Capital Ship Production Subsystem, also provides additional frontal armor. \n\n<b>Prerequisites:</b> \nCommander Rank (80 Honor points)", },
    { 
        Type = Ship, 
        ThingToBuild = "kad_nebuladrone", 
        RequiredResearch = "Garden2", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 3, 
        DisplayedName = "Spirit of the Garden", 
        Description = "<b>Description:</b> Unmanned Drone carrying a powerful nebula generator. \n\n<b>Equipment:</b> Nebula Generator \n\n<b>Prerequisites:</b> Covenant of the Garden \n2 crew members" },
    { 
        Type = Ship, 
        ThingToBuild = "kad_nebuladrone1", 
        RequiredResearch = "Garden2", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 3, 
        DisplayedName = "Spirit of the Garden", 
        Description = "<b>Description:</b> Unmanned Drone carrying a powerful nebula generator. \n\n<b>Equipment:</b> Nebula Generator \n\n<b>Prerequisites:</b> Covenant of the Garden \n2 crew members" },
    { 
        Type = Ship, 
        ThingToBuild = "kad_ressourcecollector", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Gardener", 
        Description = "<b>Description:</b> Harvesting ship. \n\n<b>Armament:</b> None \n\n<b>Prerequisites:</b> \n2 crew members" },
    { 
        Type = Ship, 
        ThingToBuild = "kad_ressourcecollector1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "Gardener", 
        Description = "<b>Description:</b> Harvesting ship. \n\n<b>Armament:</b> None \n\n<b>Prerequisites:</b> \n2 crew members" },
    { 
        Type = Ship, 
        ThingToBuild = "kad_podship", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 2, 
        DisplayedName = "Podship", 
        Description = "<b>Description:</b> Support and Repair Pod. \n\n<b>Armament:</b> None \n\n<b>Prerequisites:</b> Cathedral \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_podship1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 2, 
        DisplayedName = "Podship", 
        Description = "<b>Description:</b> Support and Repair Pod. \n\n<b>Armament:</b> None \n\n<b>Prerequisites:</b> Cathedral \n8 crew members" },
    { 
        Type = Ship, 
        ThingToBuild = "kad_multibeam_new", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 3, 
        DisplayedName = "Multibeam Frigate", 
        Description = "<b>Description:</b> Frigate armed with four Ion Cannons. \n\n<b>Armament:</b> 4x Turreted Ion Cannon \n\n<b>Prerequisites:</b> Cathedral \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_multibeam_new1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 3, 
        DisplayedName = "Multibeam Frigate", 
        Description = "<b>Description:</b> Frigate armed with four Ion Cannons. \n\n<b>Armament:</b> 4x Turreted Ion Cannon \n\n<b>Prerequisites:</b> Cathedral \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_multigun", 
        RequiredResearch = "Kadesh2", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 4, 
        DisplayedName = "Multigun Frigate", 
        Description = "<b>Description:</b> Frigate designed to deal with enemy strike craft. \n\n<b>Armament:</b> 3x Quad Splinter Turret \n\n<b>Prerequisites:</b> Cathedral and Warrior of Kadesh \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_multigun1", 
        RequiredResearch = "Kadesh2", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 4, 
        DisplayedName = "Multigun Frigate", 
        Description = "<b>Description:</b> Frigate designed to deal with enemy strike craft. \n\n<b>Armament:</b> 3x Quad Splinter Turret \n\n<b>Prerequisites:</b> Cathedral and Warrior of Kadesh \n8 crew members" }, 
     { 
         Type = Ship, 
         ThingToBuild = "kad_multibeam", 
         RequiredResearch = "Garden2", 
         RequiredShipSubSystems = "FrigateProduction", 
         DisplayPriority = 5, 
         DisplayedName = "Multiflame Frigate", 
         Description = "<b>Description:</b> Frigate armed with an area of effect weapon. Toasty! \n\n<b>Armament:</b> 2x Turreted Plasma Torch \n\n<b>Prerequisites:</b> Covenant of the Garden \n8 crew members" }, 
     { 
         Type = Ship, 
         ThingToBuild = "kad_multibeam1", 
         RequiredResearch = "Garden2", 
         RequiredShipSubSystems = "FrigateProduction", 
         DisplayPriority = 5, 
         DisplayedName = "Multiflame Frigate", 
         Description = "<b>Description:</b> Frigate armed with an area of effect weapon. Toasty! \n\n<b>Armament:</b> 2x Turreted Plasma Torch \n\n<b>Prerequisites:</b> Covenant of the Garden \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_destroyer", 
        RequiredResearch = "SupCapTech & Sajuuk1", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 16, 
        DisplayedName = "Avatar", 
        Description = "<b>Description:</b> Battlecruiser class Anti-Capital ship. \n\n<b>Armament:</b> 6x Heavy Missile Launcher, 1x Ultra-High-Energy Particle Accelerator, 4x Heavy Plasma Cannon 4x Pulsar Turret \n\n<b>Prerequisites:</b> Cathedral \nSuperCap Assemby \nNeophyte of Sajuuk \n3 officers \n30 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_destroyer1", 
        RequiredResearch = "SupCapTech & Sajuuk1", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 16, 
        DisplayedName = "Avatar", 
        Description = "<b>Description:</b> Battlecruiser class Anti-Capital ship. \n\n<b>Armament:</b> 6x Heavy Missile Launcher, 1x Ultra-High-Energy Particle Accelerator, 4x Heavy Plasma Cannon 4x Pulsar Turret \n\n<b>Prerequisites:</b> Cathedral \nSuperCap Assemby \nNeophyte of Sajuuk \n3 officers \n30 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_custodian", 
        RequiredResearch = "HyperspaceTech & Garden1", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 12, 
        DisplayedName = "Archangel", 
        Description = "<b>Description:</b> Heavy Support Class, capable of intercepting missiles. \n\n<b>Armament:</b> 10x Heavy Missile Launcher, 2x EMP Plasma Battery \n\n<b>Prerequisites:</b> Cathedral \nQuantum Scriptures \nCult of the Garden \n2 officers \n20 crew members" },
    { 
        Type = Ship, 
        ThingToBuild = "kad_custodian1", 
        RequiredResearch = "HyperspaceTech & Garden1", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 12, 
        DisplayedName = "Archangel", 
        Description = "<b>Description:</b> Heavy Support Class, capable of intercepting missiles. \n\n<b>Armament:</b> 10x Heavy Missile Launcher, 2x EMP Plasma Battery \n\n<b>Prerequisites:</b> Cathedral \nQuantum Scriptures \nCult of the Garden \n2 officers \n20 crew members" },
     { 
			  Type = SubSystem, 
			  ThingToBuild = "kad_darkrealm_1",	
			  RequiredResearch = "unbuildable", 	    
			  DisplayPriority = 0,},
     { 
			  Type = SubSystem, 
			  ThingToBuild = "kad_darkrealm_2",	
			  RequiredResearch = "unbuildable", 	    
			  DisplayPriority = 0,},
     { 
			  Type = SubSystem, 
			  ThingToBuild = "kad_darkrealm_3",	
			  RequiredResearch = "unbuildable", 	    
			  DisplayPriority = 0,},
    { 
        Type = Ship, 
        ThingToBuild = "kad_destroyer_real", 
        RequiredResearch = "HyperspaceTech", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 10, 
        DisplayedName = "Templar", 
        Description = "<b>Description:</b> Destroyer class Anti-Capital ship. \n\n<b>Armament:</b> 4x Heavy Missile Launcher, 2x Silver Cannon, 16x Maverick Launcher \n\n<b>Prerequisites:</b> Cathedral \nQuantum Scriptures \n2 officers \n20 crew members" },
    { 
        Type = Ship, 
        ThingToBuild = "kad_destroyer_real1", 
        RequiredResearch = "HyperspaceTech", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 10, 
        DisplayedName = "Templar", 
        Description = "<b>Description:</b> Destroyer class Anti-Capital ship. \n\n<b>Armament:</b> 4x Heavy Missile Launcher, 2x Silver Cannon, 16x Maverick Launcher \n\n<b>Prerequisites:</b> Cathedral \nQuantum Scriptures \n2 officers \n20 crew members" },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_sensorpod", 
        RequiredResearch = "Garden1", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 11, 
        DisplayedName = "Electronics Nacelle", 
        Description = "<b>Description:</b> Sensor Subsystem. \n\n<b>Prerequisites:</b> Cult of the Garden.", },		
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_largepod", 
        RequiredResearch = "Sajuuk1", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 31, 
        DisplayedName = "Fangs of Sajuuk", 
        Description = "<b>Description:</b> Launch System for SPIDER drones. \n\n<b>Prerequisites:</b> Neophyte of Sajuuk.", },	
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_superpod", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 33, 
        DisplayedName = "Spiritual Tabernacle", 
        Description = "<b>Description:</b> Summon the powerful Spirits to attack. \n\n<b>Prerequisites:</b> Marked of Sajuuk.", },	
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_inquisitionpod", 
        RequiredResearch = "Kadesh1", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 21, 
        DisplayedName = "Inquisition Dome", 
        Description = "<b>Description:</b> Demoralizing subsystem. \n\n<b>Prerequisites:</b> Preacher of Kadesh.", },
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_gunpod", 
        RequiredResearch = "Kadesh2", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 22, 
        DisplayedName = "Multigun Baptistery", 
        Description = "<b>Description:</b> Rapid Plasma Sprinkler. \n\n<b>Prerequisites:</b> Warrior of Kadesh.", },
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_ionpod", 
        RequiredResearch = "Kadesh3", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 23, 
        DisplayedName = "Multibeam Cupola", 
        Description = "<b>Description:</b> Vectored Anti-Capital Ion Cannon. \n\n<b>Prerequisites:</b> Crusader of Kadesh.", },
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_multipod", 
        RequiredResearch = "Garden2", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 12, 
        DisplayedName = "Multimissile Pinnacles", 
        Description = "<b>Description:</b> Launch System for Missile Barrage. \n\n<b>Prerequisites:</b> Covenant o. t. Garden.", },		
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_demopod", 
        RequiredResearch = "Sajuuk2", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 32, 
        DisplayedName = "Apocalypse Cenacle", 
        Description = "<b>Description:</b> Grants the Templar with explosion damage when destroyed. \n\n<b>Prerequisites:</b> Disciples of Sajuuk.", },		
{ 
        Type = SubSystem, 
        ThingToBuild = "kad_destroyer_nebulapod", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 13, 
        DisplayedName = "Nebula Altar", 
        Description = "<b>Description:</b> Allows the Templar to generate nebulae. \n\n<b>Prerequisites:</b> Order o. t. Garden.", },		
    { 
        Type = Ship, 
        ThingToBuild = "kad_needleship", 
        RequiredResearch = "SupCapTech", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 20, 
        DisplayedName = "Needleship", 
        Description = "<b>Description:</b> Combar Carrier capable of producing ships and fighting capital ships. \n\n<b>Armament:</b> 1x Heavy Missile Launcher, 4x Plasma Cannon, Point Defenses \n\n<b>Prerequisites:</b> Cathedral \nSuperCap Assemby \n6 officers \n50 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_needleship1", 
        RequiredResearch = "SupCapTech", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 20, 
        DisplayedName = "Needleship", 
        Description = "<b>Description:</b> Combar Carrier capable of producing ships and fighting capital ships. \n\n<b>Armament:</b> 1x Heavy Missile Launcher, 4x Plasma Cannon, Point Defenses \n\n<b>Prerequisites:</b> Cathedral \nSuperCap Assemby \n6 officers \n50 crew members" }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_needle_ion", 
        RequiredResearch = "Kadesh3", 
        RequiredShipSubSystems = "!kad_needle_figurehead", 
        RequiredFleetSubSystems = "isCaptain",
        DisplayPriority = 11, 
        DisplayedName = "Chapel", 
        Description = "<b>Description:</b> Heavy Ion Cannon Subsystem. \n\n<b>Prerequisites:</b> Crusader of Kadesh \nCaptain Rank (150 Honor points)", },
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_ion0",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_ion1",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_ion2",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_ion3",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_needle_figurehead", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "!kad_needle_ion", 
        RequiredFleetSubSystems = "isCaptain",
        DisplayPriority = 12, 
        DisplayedName = "Sajuuk's Maw", 
        Description = "<b>Description:</b> Progenitor Phased Ion Array subsystem. \n\n<b>Prerequisites:</b> Marked of Sajuuk \nCaptain Rank (150 Honor points)", },
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_figurehead0",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_figurehead1",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_figurehead2",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "kad_needle_figurehead3",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_massshield", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 13, 
        DisplayedName = "AT Field", 
        Description = "<b>Description:</b> Materialize pure mental power into Absolute Terror Field to help the Needleship survive from heavy bombardment. AT Field will consume certain amount of energy depending on how much damage it takes. \n\n<b>Prerequisites:</b> Order of the Garden.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_massshield_sphere", 
        RequiredResearch = "NeedleshipAdvancedATField", 
        RequiredShipSubSystems = "BCIonBeamTurret4", 
        DisplayPriority = 14, 
        DisplayedName = "Iron Curtain", 
        Description = "<b>Description:</b> Extends the AT Field to form an Iron Curtain covering the whole ship. The Iron Curtain will consume certain amount of energy depending on how much damage it takes. \n\n<b>Prerequisites:</b> \nOrder of the Garden \nAT Field \nIron Curtain Technology", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_avatar_progenarmor", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 10, 
        DisplayedName = "Heretical Armor", 
        Description = "<b>Description:</b> Installs Armor reinforced by progenitor technology. Boosts health and regeneration rate. \n\n<b>Prerequisites:</b> Marked of Sajuuk.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_needle_progenarmor", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 10, 
        DisplayedName = "Heretical Armor", 
        Description = "<b>Description:</b> Installs Armor reinforced by progenitor technology. Boosts health and regeneration rate. \n\n<b>Prerequisites:</b> Marked of Sajuuk.", },	
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_podship_heretic", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 10, 
        DisplayedName = "Heretical Armor", 
        Description = "<b>Description:</b> Installs Armor reinforced by progenitor technology. Boosts health and regeneration rate. \n\n<b>Prerequisites:</b> Marked of Sajuuk.", },	
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_needle_prayerpod", 
        RequiredResearch = "Kadesh1", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 9, 
        DisplayedName = "Prayer Comms", 
        Description = "<b>Description:</b> Installs a prayer comm array on this ship, allowing it to broadcast kadeshi prayers and propaganda on all frequencies. \n\n<b>Prerequisites:</b> Preacher of Kadesh.", },
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_avatar_prayerpod", 
        RequiredResearch = "Kadesh1", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 9, 
        DisplayedName = "Prayer Comms", 
        Description = "<b>Description:</b> Installs a prayer comm array on this ship, allowing it to broadcast kadeshi prayers and propaganda on all frequencies. \n\n<b>Prerequisites:</b> Preacher of Kadesh.", },		
	{ 
        Type = SubSystem, 
        ThingToBuild = "kad_podship_fighter", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Swarmer Module", 
        Description = "<b>Description:</b> Installs a prayer comm array on this ship, allowing it to broadcast kadeshi prayers and propaganda on all frequencies. \n\n<b>Prerequisites:</b> None.", },
	{ 
        Type = SubSystem, 
        ThingToBuild = "kad_podship_shield", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Nebula Generator", 
        Description = "<b>Description:</b> Installs a Sensor-Scrambling Nebula generator. \n\n<b>Prerequisites:</b> None" },
	{ 
        Type = SubSystem, 
        ThingToBuild = "kad_podship_corvette", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isLieutenant",
        DisplayPriority = 1, 
        DisplayedName = "Pod Module", 
        Description = "<b>Description:</b> Pod Production System. \n\n<b>Prerequisites:</b> \nLieutenant Rank (30 Honor points)" },			
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_needle_fighter", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 1, 
        DisplayedName = "Shrine", 
        Description = "<b>Description:</b> Swarmer Production System. \n\n<b>Prerequisites:</b> None.", },
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_hybrid", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 31, 
        DisplayedName = "Hybrid Swarmer", 
        Description = "<b>Description:</b> Swarmers fused with Heretic Tech. Powerful anti-fighter unit. \n\n<b>Armament:</b> 1x Sliver Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n6 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_hybrid1", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 31, 
        DisplayedName = "Hybrid Swarmer", 
        Description = "<b>Description:</b> Swarmers fused with Heretic Tech. Powerful anti-fighter unit. \n\n<b>Armament:</b> 1x Sliver Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n6 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_ghost", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 32, 
        DisplayedName = "Hybrid Heavy Swarmer", 
        Description = "<b>Description:</b> Swarmers fused with Heretic Tech. Powerful anti-frigate and anti-capship unit. \n\n<b>Armament:</b> 1x Plasma Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n6 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_ghost1", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 32, 
        DisplayedName = "Hybrid Heavy Swarmer", 
        Description = "<b>Description:</b> Swarmers fused with Heretic Tech. Powerful anti-frigate and anti-capship unit. \n\n<b>Armament:</b> 1x Plasma Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n6 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_pod_ghost", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 33, 
        DisplayedName = "Hybrid Pod", 
        Description = "<b>Description:</b> Pod Chassis fused with Heretic Tech. Powerful multi-purpose unit. \n\n<b>Armament:</b> 1x Phased Ion Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_pod_ghost1", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 33, 
        DisplayedName = "Hybrid Pod", 
        Description = "<b>Description:</b> Pod Chassis fused with Heretic Tech. Powerful multi-purpose unit. \n\n<b>Armament:</b> 1x Phased Ion Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n8 crew members" }, 
	{ 
        Type = Ship, 
        ThingToBuild = "kad_frig_ghost", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 34, 
        DisplayedName = "Hybrid Frigate", 
        Description = "<b>Description:</b> Multigun Frigate fused with Heretic Tech. Powerful multi-purpose unit. \n\n<b>Armament:</b> 2x Heavy Plasma Cannon, 1x Nanite Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n8 crew members" }, 
	{ 
        Type = Ship, 
        ThingToBuild = "kad_frig_ghost1", 
        RequiredResearch = "Sajuuk3", 
        RequiredShipSubSystems = "FireControlTower", 
        DisplayPriority = 34, 
        DisplayedName = "Hybrid Frigate", 
        Description = "<b>Description:</b> Multigun Frigate fused with Heretic Tech. Powerful multi-purpose unit. \n\n<b>Armament:</b> 2x Heavy Plasma Cannon, 1x Nanite Cannon \n\n<b>Prerequisites:</b> Heretical Armor \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_zealot", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 35, 
        DisplayedName = "Zealot", 
        Description = "<b>Description:</b> Advanced anti-fighter swarmer. \n\n<b>Armament:</b> 1x Sliver Cannon, 1x Pulsar Cannon, 2x Splinter Cannon \n\n<b>Prerequisites:</b> Order of the Garden \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_zealot1", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 35, 
        DisplayedName = "Zealot", 
        Description = "<b>Description:</b> Advanced anti-fighter swarmer. \n\n<b>Armament:</b> 1x Sliver Cannon, 1x Pulsar Cannon, 2x Splinter Cannon \n\n<b>Prerequisites:</b> Order of the Garden \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_Crusader", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 36, 
        DisplayedName = "Crusader", 
        Description = "<b>Description:</b> Advanced anti-capital ship swarmer. \n\n<b>Armament:</b> 1x Plasma Torpedo \n\n<b>Prerequisites:</b> Order of the Garden \n7 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_Crusader1", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 36, 
        DisplayedName = "Crusader", 
        Description = "<b>Description:</b> Advanced anti-capital ship swarmer. \n\n<b>Armament:</b> 1x Plasma Torpedo \n\n<b>Prerequisites:</b> Order of the Garden \n7 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_new", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 2, 
        DisplayedName = "Swarmer", 
        Description = "<b>Description:</b> Light Swarm Ship. Good against fighters. \n\n<b>Armament:</b> 1x Sliver Cannon \n\n<b>Prerequisites:</b> Shrine \n9 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_new1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 2, 
        DisplayedName = "Swarmer", 
        Description = "<b>Description:</b> Light Swarm Ship. Good against fighters. \n\n<b>Armament:</b> 1x Sliver Cannon \n\n<b>Prerequisites:</b> Shrine \n9 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_heavyswarmer_new", 
        RequiredResearch = "Garden1", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 4, 
        DisplayedName = "Heavy Swarmer", 
        Description = "<b>Description:</b> Heavy Swarm Ship. Good against Capital Ships. \n\n<b>Armament:</b> 3x Plasma Cannon \n\n<b>Prerequisites:</b> Shrine and Cult of the Garden \n9 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_heavyswarmer_new1", 
        RequiredResearch = "Garden1", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 4, 
        DisplayedName = "Heavy Swarmer", 
        Description = "<b>Description:</b> Heavy Swarm Ship. Good against Capital Ships. \n\n<b>Armament:</b> 3x Plasma Cannon \n\n<b>Prerequisites:</b> Shrine and Cult of the Garden \n9 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_advancedswarmer", 
        RequiredResearch = "Garden2", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 5, 
        DisplayedName = "Advanced Swarmer", 
        Description = "<b>Description:</b> Heavy Swarm Ship. Good against Corvettes. \n\n<b>Armament:</b> 3x Sliver Cannon \n\n<b>Prerequisites:</b> Shrine and Covenant of the Garden \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_advancedswarmer1", 
        RequiredResearch = "Garden2", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 5, 
        DisplayedName = "Advanced Swarmer", 
        Description = "<b>Description:</b> Heavy Swarm Ship. Good against Corvettes. \n\n<b>Armament:</b> 3x Sliver Cannon \n\n<b>Prerequisites:</b> Shrine and Covenant of the Garden \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_advancedswarmer_old", 
        RequiredResearch = "Garden2", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 6, 
        DisplayedName = "Multibeam Swarmer", 
        Description = "<b>Description:</b> Armed with three tiny ion cannons, this miniature version of the multibeam design hurts just as bad as its big brothers do. \n\n<b>Armament:</b> 3x Micro Ion Cannon \n\n<b>Prerequisites:</b> Shrine and Covenant of the Garden \n6 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_advancedswarmer_old1", 
        RequiredResearch = "Garden2", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 6, 
        DisplayedName = "Multibeam Swarmer", 
        Description = "<b>Description:</b> Armed with three tiny ion cannons, this miniature version of the multibeam design hurts just as bad as its big brothers do. \n\n<b>Armament:</b> 3x Micro Ion Cannon \n\n<b>Prerequisites:</b> Shrine and Covenant of the Garden \n6 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_blood", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 7, 
        DisplayedName = "Blood Swarmer", 
        Description = "<b>Description:</b> Swarmer piloted by bloodthirsty followers. \n\n<b>Armament:</b> 1x Blood Spatter \n\n<b>Prerequisites:</b> Order of the Garden \n25 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_swarmer_blood1", 
        RequiredResearch = "Garden3", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 7, 
        DisplayedName = "Blood Swarmer", 
        Description = "<b>Description:</b> Swarmer piloted by bloodthirsty followers. \n\n<b>Armament:</b> 1x Blood Spatter \n\n<b>Prerequisites:</b> Order of the Garden \n25 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_pulsarswarmer", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 3, 
        DisplayedName = "Pulsar Swarmer", 
        Description = "<b>Description:</b> Light Swarm Ship. Good against Corvettes. \n\n<b>Armament:</b> 1x Pulsar Cannon \n\n<b>Prerequisites:</b> Shrine \n9 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_pulsarswarmer1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 3, 
        DisplayedName = "Pulsar Swarmer", 
        Description = "<b>Description:</b> Light Swarm Ship. Good against Corvettes. \n\n<b>Armament:</b> 1x Pulsar Cannon \n\n<b>Prerequisites:</b> Shrine \n9 crew members" }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "kad_needle_corvette", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        RequiredFleetSubSystems = "isLieutenant",
        DisplayPriority = 1, 
        DisplayedName = "Temple", 
        Description = "<b>Description:</b> Corvette Production System. \n\n<b>Prerequisites:</b> \nLieutenant Rank (30 Honor points)", },
	-- actually this is the scythe now
    { 
        Type = Ship, 
        ThingToBuild = "kad_ionpod", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 3, 
        DisplayedName = "Ion Pod", 
        Description = "<b>Description:</b> Ion Beam Corvette, good against frigates. \n\n<b>Armament:</b> 1x Ion Beam Cannon \n\n<b>Prerequisites:</b> Temple \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_ionpod1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 3, 
        DisplayedName = "Ion Pod", 
        Description = "<b>Description:</b> Ion Beam Corvette, good against frigates. \n\n<b>Armament:</b> 1x Ion Beam Cannon \n\n<b>Prerequisites:</b> Temple \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_gunpod", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 2, 
        DisplayedName = "Gun Pod", 
        Description = "<b>Description:</b> Anti-Fighter Corvette. \n\n<b>Armament:</b> 4x Splinter Cannon, 1x Pulsar Cannon \n\n<b>Prerequisites:</b> Temple \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_gunpod1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 2, 
        DisplayedName = "Gun Pod", 
        Description = "<b>Description:</b> Anti-Fighter Corvette. \n\n<b>Armament:</b> 4x Splinter Cannon, 1x Pulsar Cannon \n\n<b>Prerequisites:</b> Temple \n8 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_sensorpod", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 4, 
        DisplayedName = "Electronics Pod", 
        Description = "<b>Description:</b> Corvette with electronics suite. \n\n<b>Equipment:</b> Hyperspace, Targeting Computer and Defense Field Scrambler \n\n<b>Prerequisites:</b> Temple \n2 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_sensorpod1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 4, 
        DisplayedName = "Electronics Pod", 
        Description = "<b>Description:</b> Corvette with electronics suite. \n\n<b>Equipment:</b> Hyperspace, Targeting Computer and Defense Field Scrambler \n\n<b>Prerequisites:</b> Temple \n2 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_missilepod", 
        RequiredResearch = "Garden1", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 5, 
        DisplayedName = "Missile Pod", 
        Description = "<b>Description:</b> Corvette armed with anti-capship missiles. \n\n<b>Armament:</b> 1x Heavy Missile Launcher \n\n<b>Prerequisites:</b> Temple and Cult of the Garden \n10 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_missilepod1", 
        RequiredResearch = "Garden1", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 5, 
        DisplayedName = "Missile Pod", 
        Description = "<b>Description:</b> Corvette armed with anti-capship missiles. \n\n<b>Armament:</b> 1x Heavy Missile Launcher \n\n<b>Prerequisites:</b> Temple and Cult of the Garden \n10 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_prayerpod", 
        RequiredResearch = "Kadesh1", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 6, 
        DisplayedName = "Contionator Pod", 
        Description = "<b>Description:</b> Corvette with communications suite. Broadcasts propoganda to nearby friendly ships. \n\n<b>Equipment:</b> Prayer Comms \n\n<b>Prerequisites:</b> Temple and Preacher of Kadesh \n2 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_prayerpod1", 
        RequiredResearch = "Kadesh1", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 6, 
        DisplayedName = "Contionator Pod", 
        Description = "<b>Description:</b> Corvette with communications suite. Broadcasts propoganda to nearby friendly ships. \n\n<b>Equipment:</b> Prayer Comms \n\n<b>Prerequisites:</b> Temple and Preacher of Kadesh \n2 crew members" }, 
	{ 
			Type = Ship, 
			ThingToBuild = "kad_minermissile",
			RequiredResearch = "",         
			RequiredShipSubSystems = "",  
			RequiredFleetSubSystems = "",                               
			DisplayPriority = 200,
			DisplayedName = "Miner Missile",
			Description = "<b>Description:</b> Missile Tube, Asteroid Smasher, short-range auto-aiming missile launcher, the Miner Missile automatically engages cleavable asteroids or debrises within a short radius, if there are no asteroids in the area the Miner missile will self destroy \n\n<b>Type:</b> Missile \nRange: 20 Km \nCost: 500 RUs \nBuild time: none \nMaintenance cost: none \nStrong vs: none \n\n<b>Prerequisites:</b> \nnone",},
    { 
				Type = Ship, 
				ThingToBuild = "kad_jihadi",
        RequiredResearch = "Kadesh3",         
        RequiredShipSubSystems = "",  
        RequiredFleetSubSystems = "",                               
				DisplayPriority = 250,
				DisplayedName = "Jihadi Swarmer (x5)",
				Description = "<b>Description:</b> Suicide Bomber, Anti-Capital Ship medium-range terrorist attack, very fast and cheap, the Jihadi Swarmer automatically engages enemy Capital Ships within a medium radius, the bomb does more damage if the target is close to the launching ship, if there are no enemies in the area the bomber will self destroy (5 units per strike) \n\n<b>Type:</b> Unconventional Warfare \nRange: 45 Km \nCost: 3000 RUs \nBuild time: none \nMaintenance cost: none \nStrong vs: Capital Ships \n\n<b>Prerequisites:</b> \nCrusader of Kadesh",},
    { 
        Type = Ship, 
        ThingToBuild = "kad_snail", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "Snail", 
        Description = "<b>Description:</b> Protector of the Garden, specialized in hunting capital ships. \n\n<b>Equipment:</b> 6x Spear Missile Launchers (can be upgraded to Anti-Capital Ship heavy missles) \n\n<b>Prerequisites:</b> \n4 crew members" }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_snail1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "Snail", 
        Description = "<b>Description:</b> Protector of the Garden, specialized in hunting capital ships. \n\n<b>Equipment:</b> 6x Spear Missile Launchers (can be upgraded to Anti-Capital Ship heavy missles) \n\n<b>Prerequisites:</b> \n4 crew members" }, 


	{ 
				Type = Ship, 
				ThingToBuild = "kad_minecontainer",
				RequiredResearch = "",
				RequiredFleetSubSystems = "hasminingbase",	
				DisplayPriority = 520,
				DisplayedName = "Mine Container",
				Description = "<b>Description:</b> RUs Mine Container, a very capable RUs transporter, transfers RUs from Mining Bases to the fleet\nOn Passive tactic: no auto-launch\n\n<b>Type:</b> Utility \nCost: 1250 RU \nBuild time: 65 s \nMaintenance cost: none \nStrong vs: none \n\n<b>Prerequisites:</b> \nMining Base" },	
	{ 
				Type = Ship, 
				ThingToBuild = "kad_container",
				RequiredResearch = "",
				RequiredFleetSubSystems = "hasallied",	
				DisplayPriority = 521,
				DisplayedName = "Trade Missionary",
				Description = "<b>Description:</b> RUs Trade Container, allows big Production Capital Ships to trade RUs with allied players; more RUs you have in store, more percentage (in RUs) you will gain from your trade network at any docking point; to work properly, allied players must be at a minimum distance; ideal for keep high production levels\n\n<b>Type:</b> Utility \nCost: 1250 RU \nBuild time: 65 s \nMaintenance cost: none \nStrong vs: none \n\n<b>Prerequisites:</b> \nAt least one allied player \n4 crew members" },	          			 					
	{ 
				Type = Ship, 
				ThingToBuild = "kad_container1",
				RequiredResearch = "",
				RequiredFleetSubSystems = "hasallied",	
				DisplayPriority = 521,
				DisplayedName = "Trade Missionary",
				Description = "<b>Description:</b> RUs Trade Container, allows big Production Capital Ships to trade RUs with allied players; more RUs you have in store, more percentage (in RUs) you will gain from your trade network at any docking point; to work properly, allied players must be at a minimum distance; ideal for keep high production levels\n\n<b>Type:</b> Utility \nCost: 1250 RU \nBuild time: 65 s \nMaintenance cost: none \nStrong vs: none \n\n<b>Prerequisites:</b> \nAt least one allied player \n4 crew members" },

		{ 
			  Type = Ship, 			  
			  ThingToBuild = "kad_ascensionperks",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},

	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "isLieutenant",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "isCommander",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
  { 
			  Type = SubSystem, 			  
			  ThingToBuild = "isCaptain",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  			  		        
  { 
			  Type = SubSystem, 			  
			  ThingToBuild = "isCommodore",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "isAdmiral",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
  { 
			  Type = SubSystem, 			  
			  ThingToBuild = "isFleetAdmiral",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},  
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_hgn",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_vgr",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_kad",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_rad",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "hasallied_kpr",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "fake_research",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_firepower",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_accuracy",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_health",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_repair",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_sensor",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_radiation",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "solesurvivor_speed",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military0",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,}, 
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},   	  
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military1",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},   	  
		{ 
			  Type = SubSystem, 			  
			  ThingToBuild = "military2",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},   
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank1",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,}, 
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank2",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank3",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
    { 
			  Type = SubSystem, 			  
			  ThingToBuild = "unitcapsrank4",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "unitbehavior",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "unitbehavior_downgrade",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "hyperspace",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "resource",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "buildspeed",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "resistence",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "ai_antirape",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "ai_unitcap",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},
		{ 
			  Type = SubSystem,
			  ThingToBuild = "sp_invincible",
			  RequiredResearch = "unbuildable",
			  DisplayPriority = 0,},


---planets-------------------------------------

{ 
        Type = SubSystem, 
        ThingToBuild = "planet_tech1", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "",               
        DisplayPriority = 1, 
        DisplayedName = "Genesis", 
        Description = "<b>Description:</b> Let there be light! \n\n<b>Type:</b> Planet Technology \n+ 10% Population RUs Production \nCost: 10000 RUs \nBuild time: 100 s \n\n<b>Prerequisites:</b> \nNone",},    
{ 
        Type = SubSystem, 
        ThingToBuild = "planet_tech2", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "planet_tech1",               
        DisplayPriority = 2, 
        DisplayedName = "Creature", 
        Description = "<b>Description:</b> Invigorate the planet. \n\n<b>Type:</b> Planet Technology \n+ 20% Population RUs Production \nCost: 20000 RUs \nBuild time: 200 s \n\n<b>Prerequisites:</b> \nGenesis",},   
{ 
        Type = SubSystem, 
        ThingToBuild = "planet_tech3", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "planet_tech2",               
        DisplayPriority = 3, 
        DisplayedName = "Age of Enlightenment", 
        Description = "<b>Description:</b> Enlighten the planet with belief. \n\n<b>Type:</b> Planet Technology \n+ 30% Population RUs Production \nCost: 30000 RUs \nBuild time: 300 s \n\n<b>Prerequisites:</b> \nGenesis\nCreature",},  
{ 
        Type = SubSystem, 
        ThingToBuild = "planet_tech4", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "planet_tech3",               
        DisplayPriority = 4, 
        DisplayedName = "Established Churches", 
        Description = "<b>Description:</b> Regulate the planet under the Kadeshi dogma. \n\n<b>Type:</b> Planet Technology \n+ 40% Population RUs Production \nCost: 40000 RUs \nBuild time: 400 s \n\n<b>Prerequisites:</b> \nGenesis\nCreature\nAge of Enlightenment",},    
{ 
        Type = SubSystem, 
        ThingToBuild = "planet_tech5", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "planet_tech4",               
        DisplayPriority = 5, 
        DisplayedName = "Planetary Sovereignty", 
        Description = "<b>Description:</b> Concrete the religious nature of this planet into a ritualized government. \n\n<b>Type:</b> Planet Technology \n+ 50% Population RUs Production \nCost: 50000 RUs \nBuild time: 500 s \n\n<b>Prerequisites:</b> \nGenesis\nCreature\nAge of Enlightenment\nEstablished Churches",},   
{ 
        Type = SubSystem, 
        ThingToBuild = "planet_tech6", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "planet_tech5",               
        DisplayPriority = 6, 
        DisplayedName = "Religious Freedom", 
        Description = "<b>Description:</b> Attract more religious groups by loosen the constraint. \n\n<b>Type:</b> Planet Technology \n+ 60% Population RUs Production \nCost: 60000 RUs \nBuild time: 600 s \n\n<b>Prerequisites:</b> \nGenesis\nCreature\nAge of Enlightenment\nEstablished Churches\nPlanetary Sovereignty",},   				

---crate ships (need to be in the build list or they won't have AI)-------------------------------------
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_UNH_CAStandard",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_VAY_CABattle",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_CAHeavy",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFAssault",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFCloak",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFIon",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFMine",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_FRN_FFSupport",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_UNH_FFAssault",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_UNH_FFIon",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_VAY_FFAssault",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "HWAT_VAY_FFIonArray",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_C_Bomber",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_C_Gunship",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_C_Interceptor",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_G_Bomber",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "Unit_G_Interceptor",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "hgn_pulsarfighter",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},
	{ 
			  Type = Ship, 			  
			  ThingToBuild = "hgn_shadowbomber",		
			  RequiredResearch = "unbuildable",     
			  DisplayPriority = 0,},


}
