UC_Family("Complex", 999);
UC_Family("Stop", 0);
UC_Family("Fighter", 999);
UC_Family("Corvette", 999);
UC_Family("Frigate", 999);
UC_Family("Capital", 150);
UC_ShipType("crewstation", 1);
UC_ShipType("researchstation", 1);
UC_ShipType("powerstation", 1);
UC_Family("Platform", 999);
UC_Family("Utility", 999);
UC_ShipType("ResourceCollector", 999);
UC_ShipType("ResourceController", 999);  
UC_ShipType("Core", 1);
UC_Family("Mothership",1);
UC_Family("SinglePlayerMisc", 999);
--UC_FamilyOverride("Vaygr","Fighter", 10);

UC_ShipType("TradeContainer", 9);
UC_ShipType("PowerGenerator", 9);