ambient_size = 95
battle_size = 55
special_size = 80

music_data = 
{
	size = ambient_size+battle_size+special_size,
	ambient_start = 1,
	ambient_end = ambient_size,
	battle_start = ambient_size+1,
	battle_end = ambient_size+battle_size,
	special_start = ambient_size+battle_size+1,
	special_end = ambient_size+battle_size+special_size,
	musics = 
	{

	-- ***************************************************
	-- AMBIENT
	-- ***************************************************
    {
      path = "Data:sound/music/special/Untitled",
    	name = "Untitled - Special",
      minute = 3,
      second = 58,
    },
    {
      path = "Data:sound/music/special/ERA - The Mass",
    	name = "The Mass - ERA",
      minute = 3,
      second = 44,
    },
    {
      path = "Data:sound/music/special/Nimbatus - Drone Workshop",
    	name = "Drone Workshop - Nimbatus",
      minute = 3,
      second = 15,
    },
    {
      path = "Data:sound/music/special/Nimbatus - Planet Missions",
    	name = "Planet Missions - Nimbatus",
      minute = 3,
      second = 56,
    },
    {
      path = "Data:sound/music/special/AstroPilot - Inverted Worlds",
    	name = "Inverted Worlds - SpaceEngine",
      minute = 7,
      second = 23,
    },
    {
      path = "Data:sound/music/special/A.e.r.o. - Flying Through The Universe",
    	name = "Flying Through The Universe - SpaceEngine",
      minute = 6,
      second = 59,
    },
    {
      path = "Data:sound/music/special/AstroPilot - Gravity Free",
    	name = "Gravity Free - SpaceEngine",
      minute = 7,
      second = 7,
    },
    {
      path = "Data:sound/music/special/AstroPilot - Hidden Planet",
    	name = "Hidden Planet - SpaceEngine",
      minute = 4,
      second = 39,
    },
    {
      path = "Data:sound/music/special/Lombus - Amino",
    	name = "Amino - SpaceEngine",
      minute = 4,
      second = 9,
    },
    {
      path = "Data:sound/music/special/adagiostellar",
    	name = "Adagio Stellar - Stellaris",
      minute = 4,
      second = 9,
    },
    {
      path = "Data:sound/music/special/doomsday",
    	name = "Doomsday - Stellaris",
      minute = 4,
      second = 58,
    },
    {
      path = "Data:sound/music/special/intothedark",
    	name = "Into the Dark - Stellaris",
      minute = 4,
      second = 24,
    },
    {
      path = "Data:sound/music/special/onegalaxy",
    	name = "One Galaxy - Stellaris",
      minute = 4,
      second = 41,
    },
    {
      path = "Data:sound/music/special/alphacentauri",
    	name = "Alpha Centauri - Stellaris",
      minute = 5,
      second = 24,
    },
    {
      path = "Data:sound/music/special/anewdawn",
    	name = "A New Dawn - Stellaris",
      minute = 1,
      second = 50,
    },
    {
      path = "Data:sound/music/special/assemblingthefleet",
    	name = "Assembling the Fleet - Stellaris",
      minute = 5,
      second = 15,
    },
    {
      path = "Data:sound/music/special/cradleofthegalaxy",
    	name = "Cradle of the Galaxy - Stellaris",
      minute = 5,
      second = 49,
    },
    {
      path = "Data:sound/music/special/creationandbeyond",
    	name = "Creation and Beyond - Stellaris",
      minute = 8,
      second = 31,
    },
    {
      path = "Data:sound/music/special/deepspacetravels",
    	name = "Deepspace Travels - Stellaris",
      minute = 7,
      second = 29,
    },
    {
      path = "Data:sound/music/special/distantnebula",
    	name = "Distant Nebula - Stellaris",
      minute = 7,
      second = 57,
    },
    {
      path = "Data:sound/music/special/dragonbreath",
    	name = "Dragon Breath - Stellaris",
      minute = 6,
      second = 39,
    },
    {
      path = "Data:sound/music/special/fasterthanlight",
    	name = "Faster Than Light - Stellaris",
      minute = 6,
      second = 41,
    },
    {
      path = "Data:sound/music/special/genesis",
    	name = "Genesis - Stellaris",
      minute = 6,
      second = 8,
    },
    {
      path = "Data:sound/music/special/gravitationalconstant",
    	name = "Gravitational Constant - Stellaris",
      minute = 7,
      second = 7,
    },
    {
      path = "Data:sound/music/special/infinitebeing",
    	name = "Infinite Being - Stellaris",
      minute = 7,
      second = 33,
    },
    {
      path = "Data:sound/music/special/insearchoflife",
    	name = "In Search of Life - Stellaris",
      minute = 6,
      second = 1,
    },
    {
      path = "Data:sound/music/special/journeythroughthegalaxy",
    	name = "Journey Through the Galaxy - Stellaris",
      minute = 5,
      second = 47,
    },
    {
      path = "Data:sound/music/special/luminescence_endcredits",
    	name = "Luminescence - Stellaris",
      minute = 8,
      second = 3,
    },
    {
      path = "Data:sound/music/special/pillarsofcreation",
    	name = "Pillars of Creation - Stellaris",
      minute = 12,
      second = 36,
    },
    {
      path = "Data:sound/music/special/ridingthesolarwind",
    	name = "Riding the Solar Wind - Stellaris",
      minute = 7,
      second = 8,
    },
    {
      path = "Data:sound/music/special/sigmatauri",
    	name = "Sigma Tauri - Stellaris",
      minute = 5,
      second = 36,
    },
    {
      path = "Data:sound/music/special/spatiallullaby",
    	name = "Spatial Lullaby - Stellaris",
      minute = 4,
      second = 15,
    },
    {
      path = "Data:sound/music/special/theawakened",
    	name = "The Awakened - Stellaris",
      minute = 6,
      second = 34,
    },
    {
      path = "Data:sound/music/special/thebirthofastar",
    	name = "The Birth of a Star - Stellaris",
      minute = 11,
      second = 3,
    },
    {
      path = "Data:sound/music/special/thecelestialcity",
    	name = "The Celestial City - Stellaris",
      minute = 5,
      second = 50,
    },
    {
      path = "Data:sound/music/special/theimperialfleet",
    	name = "The Imperial Fleet - Stellaris",
      minute = 5,
      second = 27,
    },
    {
      path = "Data:sound/music/special/thelaststand",
    	name = "The Last Stand - Stellaris",
      minute = 2,
      second = 50,
    },
    {
      path = "Data:sound/music/special/thetitan",
    	name = "The Titan - Stellaris",
      minute = 4,
      second = 2,
    },
    {
      path = "Data:sound/music/special/totheendsofthegalaxy",
    	name = "To the Ends of the Galaxy - Stellaris",
      minute = 6,
      second = 13,
    },
    {
      path = "Data:sound/music/special/towardsutopia",
    	name = "Towards Utopia - Stellaris",
      minute = 8,
      second = 7,
    },
    {
      path = "Data:sound/music/special/utopia_maintitle",
    	name = "Utopia Main Title - Stellaris",
      minute = 9,
      second = 36,
    },
    {
      path = "Data:sound/music/special/Infinite Warfare Soundtrack - Anthropic Universe",
    	name = "Anthropic Universe - Infinite Warfare",
    	minute = 4,
      second = 22,
    },
    {
      path = "Data:sound/music/special/into-the-oblivion",
    	name = "Into the Oblivion - Moodflow",
    	minute = 5,
      second = 0,
    },
    {
      path = "Data:sound/music/special/orbitals",
    	name = "Orbitals - Moodflow",
    	minute = 7,
      second = 53,
    },
    {
      path = "Data:sound/music/special/just-imagine",
    	name = "Just Imagine - Moodflow",
    	minute = 4,
      second = 30,
    },
    {
      path = "Data:sound/music/special/another-good-day",
    	name = "Another Good Day - Moodflow",
    	minute = 7,
      second = 37,
    },
    {
      path = "Data:sound/music/special/unsung-heroes",
    	name = "Unsung Heroes - Moodflow",
    	minute = 6,
      second = 5,
    },
    {
      path = "Data:sound/music/special/Welcome to Lunar Industries",
    	name = "Welcome to Lunar Industries - Moon",
    	minute = 7,
      second = 8,
    },
    {
      path = "Data:sound/music/special/sunshine",
    	name = "Sunshine - Sunshine",
    	minute = 4,
      second = 29,
    },
    {
      path = "Data:sound/music/special/Time",
    	name = "Time - Inception",
      minute = 4,
      second = 33,
    },
    {
      path = "Data:sound/music/special/Out into the West",
    	name = "Out into the West - TimeScapes",
    	minute = 3,
      second = 24,
    },
    {
      path = "Data:sound/music/special/Building Will",
    	name = "Building Will - Transcendence",
    	minute = 4,
      second = 13,
    },
    {
      path = "Data:sound/music/special/Star Stuff",
    	name = "Star Stuff - Cosmos: A Spacetime Odyssey",
    	minute = 4,
      second = 8,
    },
    {
      path = "Data:sound/music/special/Revelation of Immensity",
    	name = "Revelation of Immensity - Cosmos: A Spacetime Odyssey",
      minute = 3,
      second = 55,
    },
    {
      path = "Data:sound/music/special/Our Journey Is Just Beginning",
    	name = "Our Journey Is Just Beginning - Cosmos: A Spacetime Odyssey",
      minute = 3,
      second = 1,
    },
    {
      path = "Data:sound/music/special/Multiverse",
    	name = "Multiverse - Cosmos: A Spacetime Odyssey",
      minute = 2,
      second = 5,
    },
    {
      path = "Data:sound/music/special/Virgo Supercluster",
    	name = "Virgo Supercluster - Cosmos: A Spacetime Odyssey",
      minute = 4,
      second = 0,
    },
    {
      path = "Data:sound/music/special/Ryan Amon-Matilda (Elysium Soundtrack)",
    	name = "Matilda - Elysium",
    	minute = 2,
      second = 50,
    },
    {
      path = "Data:sound/music/special/A Kaleidoscope Of Mathematics",
    	name = "A Kaleidoscope Of Mathematics - A Beautiful Mind",
    	minute = 1,
      second = 35,
    },
    {
      path = "Data:sound/music/special/The Car Chase",
    	name = "The Car Chase - A Beautiful Mind",
    	minute = 2,
      second = 22,
    },
    {
      path = "Data:sound/music/special/I'm Going Home",
    	name = "I'm Going Home - Interstellar",
    	minute = 5,
      second = 48,
    },
    {
      path = "Data:sound/music/special/Day One",
    	name = "Day One - Interstellar",
    	minute = 3,
      second = 19,
    },
    {
      path = "Data:sound/music/special/2-03 Just Enough (GLA Ex1)",
    	name = "Just Enough - Zero Hour Enhanced",
    	minute = 3,
      second = 54,
    },
    
  --ambient old
    {
      path = "Data:sound/music/ambient/01. Opening",
    	name = "Opening - Homeworld 2",
      minute = 3,
      second = 5,
    },
    {
      path = "Data:sound/music/ambient/02. The Pride Of Hiigara",
    	name = "The Pride Of Hiigara - Homeworld 2",
      minute = 2,
      second = 5,
    },
    {
      path = "Data:sound/music/nis/nis03",
    	name = "The Bentusi Arrive - Homeworld 2",
    	minute = 2,
      second = 5,
    },
    {
      path = "Data:sound/music/ambient/amb_01",
      name = "Ambient 1 - Homeworld 2",
      minute = 2,
      second = 37,
    },
    {
      path = "Data:sound/music/ambient/amb_02",
    	name = "Ambient 2 - Homeworld 2",
      minute = 1,
      second = 50,
    },
    {
      path = "Data:sound/music/ambient/amb_03",
    	name = "Ambient 3 - Homeworld 2",
      minute = 2,
      second = 35,
    },
    {
      path = "Data:sound/music/ambient/amb_04",
    	name = "Ambient 4 - Homeworld 2",
      minute = 1,
      second = 50,
    },
    {
      path = "Data:sound/music/ambient/amb_05",
    	name = "Ambient 5 - Homeworld 2",
      minute = 2,
      second = 9,
    },
    {
      path = "Data:sound/music/ambient/amb_06",
    	name = "Ambient 6 - Homeworld 2",
      minute = 1,
      second = 43,
    },
    {
      path = "Data:sound/music/ambient/amb_07",
    	name = "Ambient 7 - Homeworld 2",
      minute = 2,
      second = 4,
    },
    {
      path = "Data:sound/music/ambient/amb_08",
    	name = "Ambient 8 - Homeworld 2",
      minute = 2,
      second = 21,
    },
    {
      path = "Data:sound/music/ambient/amb_12",
    	name = "Ambient 12 - Homeworld 2",
      minute = 1,
      second = 48,
    },
    {
      path = "Data:sound/music/ambient/amb_13",
    	name = "Ambient 13 - Homeworld 2",
      minute = 1,
      second = 54,
    },
    {
      path = "Data:sound/music/ambient/amb_14",
    	name = "Ambient 14 - Homeworld 2",
      minute = 2,
      second = 25,
    },
    {
      path = "Data:sound/music/ambient/staging_04",
    	name = "Staging 04 - Homeworld 2",
      minute = 2,
      second = 35,
    },
    {
      path = "Data:sound/music/ambient/staging_01",
    	name = "Staging 01 - Homeworld 2",
      minute = 2,
      second = 14,
    },
    {
      path = "Data:sound/music/ambient/32. The Keeper",
    	name = "The Keeper - Homeworld 2",
      minute = 2,
      second = 53,
    },
    {
      path = "Data:sound/music/ambient/13. Sajuuk's Identity",
    	name = "Sajuuk's Identity - Homeworld 2",
      minute = 1,
      second = 12,
    },

  --H1
    {
      path = "Data:sound/music/ambient/37. Tutorial",
    	name = "Tutorial - Homeworld",
      minute = 4,
      second = 0,
    },
    {
      path = "Data:sound/music/ambient/04. Outer Kharak System",
    	name = "Outer Kharak System - Homeworld",
      minute = 2,
      second = 39,
    },
    {
      path = "Data:sound/music/ambient/02. The Beginning",
    	name = "The Beginning - Homeworld",
      minute = 3,
      second = 8,
    },
    {
      path = "Data:sound/music/ambient/09. The Great Wastelands",
    	name = "The Great Wastelands - Homeworld",
      minute = 1,
      second = 56,
    },
    {
      path = "Data:sound/music/ambient/18. The Gardens Of Kadesh",
    	name = "The Gardens Of Kadesh - Homeworld",
      minute = 2,
      second = 15,
    },
    {
      path = "Data:sound/music/ambient/31. Bridge Of Sighs",
    	name = "Bridge Of Sighs - Homeworld",
      minute = 2,
      second = 35,
    },
    {
      path = "Data:sound/music/ambient/H1 - Heavy Radiation",
    	name = "Heavy Radiation - Homeworld",
      minute = 1,
      second = 33,
    },
    
  --HC
    {
      path = "Data:sound/music/special/continental",
    	name = "Continental - Continental",
      minute = 4,
      second = 30,
    },
    {
      path = "Data:sound/music/ambient/HC - 29",
    	name = "Ambient 29 - Cataclysm",
      minute = 1,
      second = 3,
    },
    {
      path = "Data:sound/music/special/Pale",
    	name = "Pale - Continental",
      minute = 5,
      second = 37,
    },
    {
      path = "Data:sound/music/ambient/HC - 18",
    	name = "Ambient 18 - Cataclysm",
      minute = 1,
      second = 35,
    },
    {
      path = "Data:sound/music/ambient/HC - 03",
    	name = "Ambient 3 - Cataclysm",
      minute = 2,
      second = 23,
    },
    {
      path = "Data:sound/music/ambient/HC - 11",
    	name = "Ambient 11 - Cataclysm",
      minute = 2,
      second = 32,
    },
    {
      path = "Data:sound/music/ambient/HC - 13",
    	name = "Ambient 13 - Cataclysm",
      minute = 2,
      second = 28,
    },
    
	-- ***************************************************
	-- BATTLE
	-- ***************************************************
    {
      path = "Data:sound/music/battle/25. The Lighthouse",
    	name = "The Lighthouse - Homeworld 2",
      minute = 2,
      second = 52,
    },
    {
      path = "Data:sound/music/battle/48. Battle For Sajuuk (Remixed)",
    	name = "Battle For Sajuuk (Remixed) - Homeworld 2",
      minute = 3,
      second = 43,
    },
    {
      path = "Data:sound/music/battle/battle_01",
    	name = "Battle 1 - Homeworld 2",
      minute = 4,
      second = 37,
    },
    {
      path = "Data:sound/music/battle/battle_04",
    	name = "Battle 4 - Homeworld 2",
      minute = 3,
      second = 47,
    },
    {
      path = "Data:sound/music/battle/battle_04_alt",
    	name = "Battle 4 Alt - Homeworld 2",
      minute = 3,
      second = 1,
    },
    {
      path = "Data:sound/music/battle/battle_06",
    	name = "Battle 6 - Homeworld 2",
      minute = 3,
      second = 12,
    },
    {
      path = "Data:sound/music/battle/battle_keeper",
    	name = "Battle Keeper - Homeworld 2",
      minute = 2,
      second = 58,
    },
    {
      path = "Data:sound/music/battle/battle_movers",
    	name = "Battle Movers - Homeworld 2",
      minute = 2,
      second = 39,
    },
    {
      path = "Data:sound/music/battle/battle_planetkillers",
    	name = "Battle Planet Killer - Homeworld 2",
      minute = 3,
      second = 8,
    },
    {
      path = "Data:sound/music/battle/battle_sajuuk",
    	name = "Battle Sajuuk - Homeworld 2",
      minute = 2,
      second = 42,
    },
    {
      path = "Data:sound/music/battle/18. Credits",
    	name = "Credits - Homeworld: Deserts of Kharak",
      minute = 3,
      second = 39,
    },
    {
      path = "Data:sound/music/battle/02. CP Violation",
    	name = "CP Violation - Half-Life 2",
      minute = 1,
      second = 45,
    },
    {
      path = "Data:sound/music/special/Forest Choirs",
    	name = "Forest Choirs - TimeScapes",
      minute = 2,
      second = 25,
    },
    {
      path = "Data:sound/music/special/World In Conflict-Sniper Run",
    	name = "Sniper Run - World In Conflict",
      minute = 2,
      second = 3,
    },
    {
      path = "Data:sound/music/special/Command & Conquer 3 Tiberium Wars-The Towers Must Fall",
    	name = "The Towers Must Fall - C&C3 Tiberium Wars",
      minute = 2,
      second = 39,
    },
    {
      path = "Data:sound/music/special/Command & Conquer 3 Tiberium Wars-Apocalypse",
    	name = "Apocalypse - C&C3 Tiberium Wars",
      minute = 1,
      second = 10,
    },
    {
      path = "Data:sound/music/special/Command & Conquer 3 Tiberium Wars-The Zenith",
    	name = "The Zenith - C&C3 Tiberium Wars",
      minute = 1,
      second = 5,
    },
    {
      path = "Data:sound/music/special/Mig-29 Fulcrum-Theme",
    	name = "Mig-29 Fulcrum - Mig-29 Fulcrum",
      minute = 4,
      second = 39,
    },
    {
      path = "Data:sound/music/special/Cracking the Russian Codes",
    	name = "Cracking the Russian Codes - A Beautiful Mind",
    	minute = 2,
      second = 34,
    },
    {
      path = "Data:sound/music/special/Ground Control 2 Soundtrack-Menu theme",
    	name = "Menu theme - Ground Control 2",
    	minute = 2,
      second = 9,
    },
    {
      path = "Data:sound/music/special/Ground Control 2 Operation Exouds-Track 7",
    	name = "Track 7 - Ground Control 2",
    	minute = 2,
      second = 11,
    },
    {
      path = "Data:sound/music/special/They're Not Mountains",
    	name = "They're Not Mountains - Interstellar",
    	minute = 3,
      second = 44,
    },
    {
      path = "Data:sound/music/special/Cornfield Chase",
    	name = "Cornfield Chase - Interstellar",
    	minute = 2,
      second = 7,
    },
    {
      path = "Data:sound/music/special/Natus Vincere - Jupiter Ascending",
    	name = "Natus Vincere - Jupiter Ascending",
    	minute = 2,
      second = 15,
    },
    {
      path = "Data:sound/music/special/Wake the Dawn - Jupiter Ascending",
    	name = "Wake the Dawn - Jupiter Ascending",
    	minute = 2,
      second = 23,
    },
    {
      path = "Data:sound/music/special/Shellmap",
    	name = "Shellmap - Contra",
    	minute = 2,
      second = 2,
    },
    {
      path = "Data:sound/music/special/3-09 Roll Out",
    	name = "Roll Out - Zero Hour Enhanced",
    	minute = 2,
      second = 48,
    },
    {
      path = "Data:sound/music/special/3-05 Shock And Awe",
    	name = "Shock And Awe - Zero Hour Enhanced",
    	minute = 3,
      second = 21,
    },
    {
      path = "Data:sound/music/special/3-04 Alpha Strike (USA Com7)",
    	name = "Alpha Strike - Zero Hour Enhanced",
    	minute = 5,
      second = 10,
    },
  --H1
    {
      path = "Data:sound/music/battle/H1 - Imperial Battle",
    	name = "Imperial Battle - Homeworld",
      minute = 2,
      second = 55,
    },
    {
      path = "Data:sound/music/battle/H1 - Swarmers Attack",
    	name = "Swarmers Attack - Homeworld",
      minute = 6,
      second = 47,
    },
    {
      path = "Data:sound/music/battle/H1 - Turanic Raiders (Extended)",
    	name = "Turanic Raiders (Extended) - Homeworld",
      minute = 3,
      second = 56,
    },
  --HC
    {
      path = "Data:sound/music/battle/HC - 37",
    	name = "Battle 37 - Cataclysm",
      minute = 1,
      second = 42,
    },
    {
      path = "Data:sound/music/ambient/HC - 01",
    	name = "Deep Space/Hiigara - Cataclysm",
      minute = 2,
      second = 20,
    },
    {
      path = "Data:sound/music/ambient/HC - 09",
    	name = "Gozan IV - Cataclysm",
      minute = 2,
      second = 25,
    },
    {
      path = "Data:sound/music/ambient/HC - 17",
    	name = "Naval Base Alpha - Cataclysm",
      minute = 2,
      second = 30,
    },
    {
      path = "Data:sound/music/ambient/HC - 20",
    	name = "Taiidan Battle Theme - Cataclysm",
    	minute = 2,
      second = 54,
    },
    {
      path = "Data:sound/music/ambient/HC - 21",
    	name = "Turanic Battle 1 - Cataclysm",
    	minute = 3,
      second = 10,
    },
    {
      path = "Data:sound/music/ambient/HC - 23",
    	name = "Beast Battle - Cataclysm",
    	minute = 2,
      second = 26,
    },
    {
      path = "Data:sound/music/ambient/HC - 24",
    	name = "Bentusi Attack - Cataclysm",
    	minute = 2,
      second = 5,
    },
    {
      path = "Data:sound/music/ambient/HC - 25",
    	name = "Sojent-Ra Theme - Cataclysm",
    	minute = 2,
      second = 7,
    },
    {
      path = "Data:sound/music/ambient/HC - 39",
    	name = "Cataclysm Credits - Cataclysm",
    	minute = 3,
      second = 10,
    },
    {
      path = "Data:sound/music/special/Ashes_Escalation_Menu.1",
    	name = "Escalation Menu 1 - Ashes of the Singularity",
      minute = 3,
      second = 11,
    },
    {
      path = "Data:sound/music/special/09-tim_wynn_-_red_rock_for_mother_russia-umt",
    	name = "Red Rock For Mother Russia - Red Alert 3",
      minute = 4,
      second = 17,
    },
    {
      path = "Data:sound/music/special/02-frank_klepacki_-_hell_march_3-umt",
    	name = "Hell March 3 - Red Alert 3",
      minute = 3,
      second = 35,
    },
    {
      path = "Data:sound/music/special/01-james_hannigan_-_red_alert_3_theme_soviet_march-umt",
    	name = "Soviet March - Red Alert 3",
      minute = 2,
      second = 47,
    },
    {
      path = "Data:sound/music/special/20-james_hannigan_-_the_empire_strikes-umt",
    	name = "The Empire Strikes - Red Alert 3",
      minute = 3,
      second = 47,
    },
    {
      path = "Data:sound/music/special/17-tim_wynn_-_lying_in_wait-umt",
    	name = "Lying In Wait - Red Alert 3",
      minute = 1,
      second = 8,
    },
    {
      path = "Data:sound/music/special/Audiomachine - Breath and Life",
    	name = "Breath and Life - Audiomachine",
      minute = 1,
      second = 51,
    },
    {
      path = "Data:sound/music/special/Two Steps From Hell - El Dorado (Skyworld)(Epic Orchestral Hybrid)",
    	name = "El Dorado - Two Steps From Hell",
      minute = 4,
      second = 15,
    },
    {
      path = "Data:sound/music/special/Two Steps From Hell - Dragon Rider _Archangel_",
    	name = "Dragon Rider - Two Steps From Hell",
      minute = 1,
      second = 53,
    },
    {
      path = "Data:sound/music/special/Two Steps from Hell - Heart of Courage",
    	name = "Heart of Courage - Two Steps From Hell",
      minute = 2,
      second = 0,
    },
    {
      path = "Data:sound/music/special/Two Steps From Hell - Jump",
    	name = "Jump - Two Steps From Hell",
      minute = 4,
      second = 38,
    },
    {
      path = "Data:sound/music/special/Two Steps From Hell - Never Back Down",
    	name = "Never Back Down - Two Steps From Hell",
      minute = 2,
      second = 59,
    },
    {
      path = "Data:sound/music/special/Two Steps From Hell - Protectors of the Earth",
    	name = "Protectors of the Earth - Two Steps From Hell",
      minute = 2,
      second = 52,
    },
    
	-- ***************************************************
	-- SPECIAL
	-- ***************************************************
    {
      path = "Data:sound/music/special/53. The Age Of S'Jet",
    	name = "The Age Of S'Jet - Homeworld 2",
      minute = 1,
      second = 58,
    },
    {
      path = "Data:sound/music/special/Samuel Barber-Adagio For Strings",
    	name = "Adagio for Strings - Homeworld",
      minute = 6,
      second = 22,
    },
    {
      path = "Data:sound/music/special/Steve Jablonsky - The Art of War",
    	name = "The Art of War - Battleship",
      minute = 4,
      second = 33,
    },
    {
      path = "Data:sound/music/special/the Blood of Cuchulainn",
    	name = "the Blood of Cuchulainn - Special",
      minute = 4,
      second = 3,
    },
    {
      path = "Data:sound/music/special/acezero",
    	name = "Zero - Ace Combat Zero",
      minute = 5,
      second = 37,
    },
    {
      path = "Data:sound/music/special/Canon",
    	name = "Canon - Special",
      minute = 4,
      second = 57,
    },
    {
      path = "Data:sound/music/special/ROTR_07",
    	name = "Rise of the Reds - Special",
      minute = 4,
      second = 6,
    },
    {
      path = "Data:sound/music/special/Crimson_Tide",
    	name = "Crimson Tide - Crimson Tide",
      minute = 7,
      second = 32,
    },
    {
      path = "Data:sound/music/special/Stuart Chatwood - the 1st fight",
    	name = "the 1st Fight - Special",
      minute = 3,
      second = 40,
    },
    {
      path = "Data:sound/music/special/Teque - 9mm from heaven",
    	name = "9mm from Heaven - Special",
      minute = 4,
      second = 20,
    },
    {
      path = "Data:sound/music/special/ride-the-worm",
    	name = "Ride the Worm - Battle for Dune",
      minute = 5,
      second = 35,
    },
    {
      path = "Data:sound/music/special/not-an-option",
    	name = "Not an Option - Battle for Dune",
      minute = 3,
      second = 52,
    },
    {
      path = "Data:sound/music/special/the-war-begins",
    	name = "the War Begins - Battle for Dune",
      minute = 4,
      second = 33,
    },
    {
      path = "Data:sound/music/special/Kokyou he",
    	name = "Kokyou He - the Secret of Blue Water",
      minute = 4,
      second = 58,
    },
    {
      path = "Data:sound/music/special/Teque - Wisal_the_Electric_Lov",
    	name = "Wisal the Electric Lov - Special",
      minute = 2,
      second = 59,
    },
    {
      path = "Data:sound/music/special/Hummel-gets-the-rockets",
    	name = "the Rock - the Rock",
      minute = 6,
      second = 23,
    },
    {
      path = "Data:sound/music/special/Dream_Within_A_Dream-Hans_Zimmer",
    	name = "Dream within a Dream - Inception",
      minute = 5,
      second = 4,
    },
    {
      path = "Data:sound/music/special/DreamIsCollapsing",
    	name = "Dream Is Collapsing - Inception",
      minute = 2,
      second = 23,
    },
    {
      path = "Data:sound/music/special/Arrival_To_Earth",
    	name = "Arrival to Earth - Transformer",
      minute = 5,
      second = 24,
    },
    {
      path = "Data:sound/music/special/a step forward into terror",
    	name = "A Step Forward Into Terror - Neon Genesis Evangelion",
      minute = 1,
      second = 48,
    },
    {
      path = "Data:sound/music/special/Pacific Rim",
    	name = "Pacific Rim - Pacific Rim",
      minute = 4,
      second = 52,
    },
    {
      path = "Data:sound/music/special/decisive battle",
    	name = "Decisive Battle - Neon Genesis Evangelion",
      minute = 2,
      second = 20,
    },
    {
      path = "Data:sound/music/special/Hazardous Environments",
    	name = "Hazardous Environments - Half-Life 2",
      minute = 1,
      second = 23,
    },
    {
      path = "Data:sound/music/special/Gipsy Danger",
    	name = "Gipsy Danger - Pacific Rim",
      minute = 3,
      second = 17,
    },
    {
      path = "Data:sound/music/special/The Breach",
    	name = "The Breach - Pacific Rim",
      minute = 3,
      second = 11,
    },
    {
      path = "Data:sound/music/special/Battlefield 1942",
    	name = "Battlefield 1942 - Battlefield 1942",
      minute = 4,
      second = 7,
    },
    {
      path = "Data:sound/music/special/Ordos",
    	name = "A Plan of Attack - Battle for Dune",
      minute = 3,
      second = 59,
    },
    {
      path = "Data:sound/music/special/Ender's war",
    	name = "Ender's War - Ender's Game",
      minute = 3,
      second = 24,
    },
    {
      path = "Data:sound/music/special/USA_11",
    	name = "USA_11 - C&C Generals",
      minute = 3,
      second = 5,
    },
    {
      path = "Data:sound/music/special/USA_09",
    	name = "USA_09 - C&C Generals",
      minute = 3,
      second = 9,
    },
    {
      path = "Data:sound/music/special/GLA_09",
    	name = "GLA_09 - C&C Generals",
      minute = 2,
      second = 41,
    },
    {
      path = "Data:sound/music/special/GLA_06",
    	name = "GLA_06 - C&C Generals",
      minute = 3,
      second = 10,
    },
    {
      path = "Data:sound/music/special/The Avengers",
    	name = "The Avengers - Avengers",
    	minute = 2,
      second = 1,
    },
    {
      path = "Data:sound/music/special/K-Pax",
    	name = "Grand Central - K-Pax",
    	minute = 4,
      second = 36,
    },
    {
      path = "Data:sound/music/special/Battle - Steve Jablonsky",
    	name = "Battle - Transformer",
    	minute = 3,
      second = 38,
    },
    {
      path = "Data:sound/music/special/My Name Is Lincoln",
    	name = "My Name Is Lincoln - My Name Is Lincoln",
    	minute = 3,
      second = 35,
  	},
    {
      path = "Data:sound/music/special/President's Speech",
    	name = "President's Speech - The Day After Tomorrow",
    	minute = 4,
      second = 16,
    },
    {
      path = "Data:sound/music/battle/staging_01",
    	name = "Complex Menu Theme - Special",
    	minute = 3,
      second = 5,
    },
    {
      path = "Data:sound/music/special/Arcade",
    	name = "Arcade - Man of Steel",
    	minute = 7,
      second = 17,
    },
    {
      path = "Data:sound/music/special/Flight",
    	name = "Flight - Man of Steel",
    	minute = 4,
      second = 15,
    },
    {
      path = "Data:sound/music/special/Ryan Amon-Breaking a Promise (Elysium Soundtrack)",
    	name = "Breaking a Promise - Elysium",
    	minute = 3,
      second = 14,
    },
    {
      path = "Data:sound/music/special/Ryan Amon-Elysium (Elysium Soundtrack)",
    	name = "Elysium - Elysium",
    	minute = 3,
      second = 44,
    },
    {
      path = "Data:sound/music/special/EVA Soundtrack 1 - EVA-02",
    	name = "EVA-02 - Neon Genesis Evangelion",
    	minute = 1,
      second = 56,
    },
    {
      path = "Data:sound/music/special/EVA Soundtrack 1 - NERV",
    	name = "NERV - Neon Genesis Evangelion",
    	minute = 1,
      second = 55,
    },
    {
      path = "Data:sound/music/special/Terraforming",
    	name = "Terraforming - Man of Steel",
    	minute = 9,
      second = 45,
    },
    {
      path = "Data:sound/music/special/The Surface Of Sun",
    	name = "The Surface of the Sun - Sunshine",
    	minute = 3,
      second = 56,
    },
    {
      path = "Data:sound/music/special/EVA Soundtrack 2 - Magmadiver",
    	name = "Magmadiver - Neon Genesis Evangelion",
    	minute = 2,
      second = 20,
    },
    {
      path = "Data:sound/music/special/Requiem for a dream",
    	name = "Lux Aeterna - Requiem for a Dream",
    	minute = 6,
      second = 27,
    },
    {
      path = "Data:sound/music/special/Ender's promise",
    	name = "Ender's Promise - Ender's Game",
    	minute = 5,
      second = 7,
    },
    {
      path = "Data:sound/music/special/fay",
    	name = "EXEC_COSMOFLIPS/. - Ar Tonelico",
      minute = 3,
      second = 32,
    },
    {
      path = "Data:sound/music/special/Will and Elizabeth",
    	name = "Will and Elizabeth - Pirates of the Caribbean",
    	minute = 2,
      second = 4,
    },
    {
      path = "Data:sound/music/special/He's a pirate",
    	name = "He's a pirate - Pirates of the Caribbean",
    	minute = 1,
      second = 31,
    },
    {
      path = "Data:sound/music/special/Blood Ritual",
    	name = "Blood Ritual - Pirates of the Caribbean",
    	minute = 3,
      second = 31,
    },
    {
      path = "Data:sound/music/special/Jack Sparrow",
    	name = "Jack Sparrow - Pirates of the Caribbean",
    	minute = 6,
      second = 4,
    },
    {
      path = "Data:sound/music/special/One Simple Idea",
    	name = "One Simple Idea - Inception",
    	minute = 2,
      second = 27,
    },
    {
      path = "Data:sound/music/special/Near Centaurus",
    	name = "Near Centaurus - TimeScapes",
    	minute = 9,
      second = 55,
    },
    {
      path = "Data:sound/music/special/Crystal Skies",
    	name = "Crystal Skies - TimeScapes",
    	minute = 7,
      second = 45,
    },
    {
      path = "Data:sound/music/special/TimeScapes",
    	name = "TimeScapes - TimeScapes",
    	minute = 5,
      second = 4,
    },
    {
      path = "Data:sound/music/special/The Approaching Light",
    	name = "The Approaching Light - TimeScapes",
    	minute = 3,
      second = 37,
    },
    {
      path = "Data:sound/music/special/the-machine",
    	name = "the Machine - Battle for Dune",
      minute = 4,
      second = 50,
    },
    {
      path = "Data:sound/music/special/legacy",
    	name = "Legacy - Battle for Dune",
      minute = 6,
      second = 15,
    },
    {
      path = "Data:sound/music/special/aimbot",
    	name = "Aimbot - Special",
      minute = 1,
      second = 57,
    },
    {
      path = "Data:sound/music/special/disappear",
    	name = "Disappear - Nero",
      minute = 3,
      second = 12,
    },
    {
      path = "Data:sound/music/special/tristan",
    	name = "Tristan - Invincible",
      minute = 2,
      second = 48,
    },
    {
      path = "Data:sound/music/special/false king",
    	name = "False King - Invincible",
      minute = 2,
      second = 19,
    },
    {
      path = "Data:sound/music/special/The Prodigy-Medusa's Path",
    	name = "Medusa's Path - Special",
      minute = 5,
      second = 36,
    },
    {
      path = "Data:sound/music/special/ace-combat-zero-26-end-credits",
    	name = "End Credits - Ace Combat Zero",
      minute = 5,
      second = 49,
    },
    {
      path = "Data:sound/music/special/Alicia Discovers Nash's Dark World",
    	name = "Alicia Discovers Nash's Dark World - A Beautiful Mind",
    	minute = 8,
      second = 29,
    },
    {
      path = "Data:sound/music/special/Closing Credits",
    	name = "Closing Credits - A Beautiful Mind",
    	minute = 4,
      second = 34,
    },
    {
      path = "Data:sound/music/special/Creating Governing Dynamics",
    	name = "Creating Governing Dynamics - A Beautiful Mind",
    	minute = 4,
      second = 55,
    },
    {
      path = "Data:sound/music/special/No Time For Caution",
    	name = "No Time For Caution - Interstellar",
    	minute = 4,
      second = 6,
    },
    {
      path = "Data:sound/music/special/Detach",
    	name = "Detach - Interstellar",
    	minute = 6,
      second = 43,
    },
    {
      path = "Data:sound/music/special/max richter on the nature of daylight",
    	name = "On the Nature of Daylight - Arrival",
    	minute = 6,
      second = 11,
    },
    {
      path = "Data:sound/music/special/02-an-end-once-and-for-all",
    	name = "An End, Once And For All - Mass Effect 3",
      minute = 4,
      second = 42,
    },
    {
      path = "Data:sound/music/special/Haalee'sTheme",
    	name = "Haalee's Theme - Ashes of the Singularity",
      minute = 3,
      second = 26,
    },
    {
      path = "Data:sound/music/special/Thomas Bergersen - Empire of Angels _Sun_",
    	name = "Empire of Angels - Two Steps From Hell",
      minute = 5,
      second = 16,
    },
    {
      path = "Data:sound/music/special/Two Steps From Hell - Victory",
    	name = "Victory - Two Steps From Hell",
      minute = 5,
      second = 28,
    },
    {
      path = "Data:sound/music/special/VANGELIS - Conquest of Paradise_HD",
    	name = "Conquest of Paradise - 1492: Conquest of Paradise",
      minute = 4,
      second = 12,
    },
    {
      path = "Data:sound/music/special/01 Fallout 4 Main Theme",
    	name = "Fallout 4 Main Theme - Fallout 4",
      minute = 3,
      second = 2,
    },
    {
      path = "Data:sound/music/special/Dr_ Dre Ft Snoop Dogg-The Next Episode _lyrics_",
    	name = "The Next Episode - Special",
      minute = 2,
      second = 45,
    },
    
	},
}