AttackStyleName = AttackRun
Data = 
{ 
    howToBreakFormation = StraightAndScatter,  
    faceTargetHorizontal = 1, 
    faceTargetVertical = 1,  
    maxBreakDistance = 0, 
    distanceFromTargetToBreak = 0, 
    safeDistanceFromTargetToDoActions = 0, 
    useTargetUp = 0, 
    coordSysToUse = Target, 
    horizontalMin = 0.2, 
    horizontalMax = 0.6, 
    horizontalFlip = 1, 
    verticalMin = 0.4, 
    verticalMax = 0.7, 
    verticalFlip = 0,  
    RandomActions = {},         
    BeingAttackedActions = {}, 
    FiringActions = {}, }
